WITH subcategory_seed(category_slug, slug, name, sort_order) AS (
  VALUES
    ('podveska', 'amortizatory', 'Амортизаторы', 10),
    ('podveska', 'pruzhiny', 'Пружины', 20),
    ('podveska', 'ressory', 'Рессоры', 30),
    ('podveska', 'stoyki', 'Стойки', 40),
    ('podveska', 'podshipniki', 'Подшипники', 50),
    ('podveska', 'stupicy', 'Ступицы и кулаки', 60),
    ('podveska', 'saylentbloki', 'Сайлентблоки', 70),
    ('podveska', 'rychagi', 'Рычаги', 80),
    ('podveska', 'sharovye-opory', 'Шаровые опоры', 90),
    ('podveska', 'rulevye-nakonechniki', 'Рулевые наконечники', 100),
    ('podveska', 'rulevye-tyagi', 'Рулевые тяги', 110),
    ('podveska', 'shlangi-gur', 'Шланги ГУР', 120),
    ('podveska', 'remkomplekty-gur', 'Ремкомплекты ГУР', 130),
    ('podveska', 'prochaya-podveska', 'Прочая подвеска', 140),
    ('elektrika', 'akkumulyatory', 'Аккумуляторы', 10),
    ('elektrika', 'generatory', 'Генераторы', 20),
    ('elektrika', 'startery', 'Стартеры', 30),
    ('elektrika', 'lampy', 'Лампы', 40),
    ('elektrika', 'osveshchenie', 'Освещение', 50),
    ('elektrika', 'rele', 'Реле', 60),
    ('elektrika', 'predohraniteli', 'Предохранители', 70),
    ('elektrika', 'datchiki', 'Датчики', 80),
    ('elektrika', 'provodka', 'Проводка', 90),
    ('elektrika', 'svechi-zazhiganiya', 'Свечи зажигания', 100),
    ('elektrika', 'signalizatsii', 'Сигнализации', 110),
    ('elektrika', 'prochaya-elektrika', 'Прочая электрика', 120),
    ('filtry-i-masla', 'masla', 'Масла', 10),
    ('filtry-i-masla', 'maslyanye-filtry', 'Масляные фильтры', 20),
    ('filtry-i-masla', 'vozdushnye-filtry', 'Воздушные фильтры', 30),
    ('filtry-i-masla', 'toplivnye-filtry', 'Топливные фильтры', 40),
    ('filtry-i-masla', 'salonnye-filtry', 'Салонные фильтры', 50),
    ('filtry-i-masla', 'smazki', 'Смазки', 60),
    ('filtry-i-masla', 'zhidkosti', 'Технические жидкости', 70),
    ('tormoznaya-sistema', 'tormoznye-diski', 'Тормозные диски', 10),
    ('tormoznaya-sistema', 'tormoznye-kolodki', 'Тормозные колодки', 20),
    ('tormoznaya-sistema', 'supporty', 'Суппорты', 30),
    ('tormoznaya-sistema', 'barabany', 'Барабаны', 40),
    ('tormoznaya-sistema', 'cilindry', 'Цилиндры', 50),
    ('tormoznaya-sistema', 'shlangi', 'Шланги', 60),
    ('tormoznaya-sistema', 'tormoznye-trubki', 'Тормозные трубки', 70),
    ('tormoznaya-sistema', 'remkomplekty-tormoznoy-sistemy', 'Ремкомплекты тормозной системы', 80),
    ('tormoznaya-sistema', 'tormoznye-shtucery', 'Тормозные штуцеры', 90),
    ('tormoznaya-sistema', 'ruchnoy-tormoz', 'Ручной тормоз', 100),
    ('tormoznaya-sistema', 'prochaya-tormoznaya-sistema', 'Прочая тормозная система', 110),
    ('kuzov-i-optika', 'fary', 'Фары', 10),
    ('kuzov-i-optika', 'fonari', 'Фонари', 20),
    ('kuzov-i-optika', 'zerkala', 'Зеркала', 30),
    ('kuzov-i-optika', 'stekla', 'Стекла', 40),
    ('kuzov-i-optika', 'reshetki', 'Решетки', 50),
    ('kuzov-i-optika', 'bampery', 'Бамперы', 60),
    ('kuzov-i-optika', 'moldingi', 'Молдинги', 70),
    ('kuzov-i-optika', 'podkrylki-i-bryzgoviki', 'Подкрылки и брызговики', 80),
    ('kuzov-i-optika', 'zamki-i-ruchki', 'Замки и ручки', 90),
    ('kuzov-i-optika', 'obves-i-dekor', 'Обвес и декор', 100),
    ('kuzov-i-optika', 'elementy-salona', 'Элементы салона', 110),
    ('kuzov-i-optika', 'emblemy', 'Эмблемы', 120),
    ('kuzov-i-optika', 'povtoriteli', 'Повторители', 130),
    ('kuzov-i-optika', 'stekla-far-i-fonarey', 'Стёкла фар и фонарей', 140),
    ('kuzov-i-optika', 'kryshki-i-korpusa-optiki', 'Крышки и корпуса оптики', 150),
    ('kuzov-i-optika', 'kronshteyny-i-krepleniya', 'Кронштейны и крепления', 160),
    ('kuzov-i-optika', 'kuzovnye-detali', 'Кузовные детали', 170),
    ('dvigatel-i-transmissiya', 'remni', 'Ремни', 10),
    ('dvigatel-i-transmissiya', 'prokladki', 'Прокладки', 20),
    ('dvigatel-i-transmissiya', 'nasosy', 'Насосы', 30),
    ('dvigatel-i-transmissiya', 'sceplenie', 'Сцепление', 40),
    ('dvigatel-i-transmissiya', 'kpp', 'КПП', 50),
    ('dvigatel-i-transmissiya', 'ohlazhdenie', 'Охлаждение', 60),
    ('dvigatel-i-transmissiya', 'patrubki-i-shlangi-ohlazhdeniya', 'Патрубки и шланги охлаждения', 70),
    ('dvigatel-i-transmissiya', 'homuty-ohlazhdeniya', 'Хомуты охлаждения', 80),
    ('dvigatel-i-transmissiya', 'kryshki-i-probki-ohlazhdeniya', 'Крышки и пробки охлаждения', 90),
    ('dvigatel-i-transmissiya', 'toplivnaya-sistema', 'Топливная система', 100),
    ('dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 'Выхлопная система', 110),
    ('dvigatel-i-transmissiya', 'detali-dvigatelya', 'Детали двигателя', 120),
    ('dvigatel-i-transmissiya', 'detali-transmissii', 'Детали трансмиссии', 130),
    ('aksessuary', 'chehly', 'Чехлы', 10),
    ('aksessuary', 'kovriki', 'Коврики', 20),
    ('aksessuary', 'kompressory', 'Компрессоры', 30),
    ('aksessuary', 'nasosy', 'Насосы', 40),
    ('aksessuary', 'instrumenty', 'Инструменты', 50),
    ('aksessuary', 'shiny-i-diski', 'Шины и диски', 60),
    ('aksessuary', 'ramki-nomerov', 'Рамки номеров', 70),
    ('aksessuary', 'avtohimiya', 'Автохимия', 80),
    ('aksessuary', 'organayzery', 'Органайзеры', 90),
    ('aksessuary', 'bezopasnost', 'Безопасность', 100),
    ('aksessuary', 'prochie-aksessuary', 'Прочие аксессуары', 110),
    ('ves-assortiment', 'vse-tovary', 'Все товары', 10)
)
INSERT INTO subcategories (category_id, slug, name, sort_order)
SELECT categories.id, subcategory_seed.slug, subcategory_seed.name, subcategory_seed.sort_order
FROM subcategory_seed
JOIN categories ON categories.slug = subcategory_seed.category_slug
ON CONFLICT (category_id, slug) DO UPDATE
SET
  name = EXCLUDED.name,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

WITH rule_seed(pattern, category_slug, subcategory_slug, priority) AS (
  VALUES
    ('трубка торм', 'tormoznaya-sistema', 'tormoznye-trubki', 3),
    ('тормозная трубка', 'tormoznaya-sistema', 'tormoznye-trubki', 3),
    ('трубки торм', 'tormoznaya-sistema', 'tormoznye-trubki', 3),
    ('штуцер торм', 'tormoznaya-sistema', 'tormoznye-shtucery', 4),
    ('штуцер прокач', 'tormoznaya-sistema', 'tormoznye-shtucery', 4),
    ('тройник торм', 'tormoznaya-sistema', 'tormoznye-shtucery', 4),
    ('ремкомплект суппорт', 'tormoznaya-sistema', 'remkomplekty-tormoznoy-sistemy', 5),
    ('ремкомплект торм', 'tormoznaya-sistema', 'remkomplekty-tormoznoy-sistemy', 5),
    ('рем комплект торм', 'tormoznaya-sistema', 'remkomplekty-tormoznoy-sistemy', 5),
    ('рем. к-т торм', 'tormoznaya-sistema', 'remkomplekty-tormoznoy-sistemy', 5),
    ('рем к-т торм', 'tormoznaya-sistema', 'remkomplekty-tormoznoy-sistemy', 5),
    ('ремкомплект цилиндра торм', 'tormoznaya-sistema', 'remkomplekty-tormoznoy-sistemy', 5),
    ('ремкомплект главного торм', 'tormoznaya-sistema', 'remkomplekty-tormoznoy-sistemy', 5),
    ('шланг гур', 'podveska', 'shlangi-gur', 6),
    ('шланг гура', 'podveska', 'shlangi-gur', 6),
    ('трубка гур', 'podveska', 'shlangi-gur', 6),
    ('ремкомплект гур', 'podveska', 'remkomplekty-gur', 7),
    ('ремкомплект гура', 'podveska', 'remkomplekty-gur', 7),
    ('рем комплект гур', 'podveska', 'remkomplekty-gur', 7),
    ('рем. к-т гур', 'podveska', 'remkomplekty-gur', 7),
    ('рем к-т гур', 'podveska', 'remkomplekty-gur', 7),
    ('ремкомплект рулевой рейки', 'podveska', 'remkomplekty-gur', 7),
    ('рулевая тяга', 'podveska', 'rulevye-tyagi', 8),
    ('тяга рул', 'podveska', 'rulevye-tyagi', 8),
    ('патрубок радиатор', 'dvigatel-i-transmissiya', 'patrubki-i-shlangi-ohlazhdeniya', 8),
    ('патрубок охлажд', 'dvigatel-i-transmissiya', 'patrubki-i-shlangi-ohlazhdeniya', 8),
    ('патрубки охлажд', 'dvigatel-i-transmissiya', 'patrubki-i-shlangi-ohlazhdeniya', 8),
    ('патрубок отопител', 'dvigatel-i-transmissiya', 'patrubki-i-shlangi-ohlazhdeniya', 8),
    ('патрубки печки', 'dvigatel-i-transmissiya', 'patrubki-i-shlangi-ohlazhdeniya', 8),
    ('шланг радиатор', 'dvigatel-i-transmissiya', 'patrubki-i-shlangi-ohlazhdeniya', 8),
    ('шланг охлажд', 'dvigatel-i-transmissiya', 'patrubki-i-shlangi-ohlazhdeniya', 8),
    ('тройник радиатор', 'dvigatel-i-transmissiya', 'patrubki-i-shlangi-ohlazhdeniya', 8),
    ('тройник охлажд', 'dvigatel-i-transmissiya', 'patrubki-i-shlangi-ohlazhdeniya', 8),
    ('хомут радиатор', 'dvigatel-i-transmissiya', 'homuty-ohlazhdeniya', 9),
    ('хомут патруб', 'dvigatel-i-transmissiya', 'homuty-ohlazhdeniya', 9),
    ('хомут охлажд', 'dvigatel-i-transmissiya', 'homuty-ohlazhdeniya', 9),
    ('крышка радиатор', 'dvigatel-i-transmissiya', 'kryshki-i-probki-ohlazhdeniya', 9),
    ('крышка расширител', 'dvigatel-i-transmissiya', 'kryshki-i-probki-ohlazhdeniya', 9),
    ('крышка бачка охлажд', 'dvigatel-i-transmissiya', 'kryshki-i-probki-ohlazhdeniya', 9),
    ('крышка бачка расшир', 'dvigatel-i-transmissiya', 'kryshki-i-probki-ohlazhdeniya', 9),
    ('пробка радиатор', 'dvigatel-i-transmissiya', 'kryshki-i-probki-ohlazhdeniya', 9),
    ('пробка расширител', 'dvigatel-i-transmissiya', 'kryshki-i-probki-ohlazhdeniya', 9),
    ('пробка бачка охлажд', 'dvigatel-i-transmissiya', 'kryshki-i-probki-ohlazhdeniya', 9),
    ('пробка бачка расшир', 'dvigatel-i-transmissiya', 'kryshki-i-probki-ohlazhdeniya', 9),
    ('крышка бардач', 'kuzov-i-optika', 'elementy-salona', 9),
    ('крышка трамблер', 'elektrika', 'prochaya-elektrika', 9),
    ('крышка трамблера', 'elektrika', 'prochaya-elektrika', 9),
    ('крышка распределителя', 'elektrika', 'prochaya-elektrika', 9),
    ('крышка гбц', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 9),
    ('крышка клапан', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 9),
    ('клапанная крышка', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 9),
    ('ремкомплект карбюратор', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 9),
    ('рем комплект карбюратор', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 9),
    ('шланг топлив', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 9),
    ('трубка топлив', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 9),
    ('кольцо поршн', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 9),
    ('кольца поршн', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 9),
    ('кольцо синхронизатор', 'dvigatel-i-transmissiya', 'detali-transmissii', 9),
    ('стекло фары', 'kuzov-i-optika', 'stekla-far-i-fonarey', 9),
    ('стекло фар', 'kuzov-i-optika', 'stekla-far-i-fonarey', 9),
    ('стекло фонаря', 'kuzov-i-optika', 'stekla-far-i-fonarey', 9),
    ('стекло фонар', 'kuzov-i-optika', 'stekla-far-i-fonarey', 9),
    ('корпус фары', 'kuzov-i-optika', 'kryshki-i-korpusa-optiki', 9),
    ('корпус фонаря', 'kuzov-i-optika', 'kryshki-i-korpusa-optiki', 9),
    ('крышка фары', 'kuzov-i-optika', 'kryshki-i-korpusa-optiki', 9),
    ('крышка фонаря', 'kuzov-i-optika', 'kryshki-i-korpusa-optiki', 9),
    ('повторитель', 'kuzov-i-optika', 'povtoriteli', 9),
    ('поворотник', 'kuzov-i-optika', 'povtoriteli', 9),
    ('указатель поворота', 'kuzov-i-optika', 'povtoriteli', 9),
    ('эмблема', 'kuzov-i-optika', 'emblemy', 9),
    ('шильдик', 'kuzov-i-optika', 'emblemy', 9),
    ('знак', 'kuzov-i-optika', 'emblemy', 130),
    ('кронштейн фары', 'kuzov-i-optika', 'kronshteyny-i-krepleniya', 10),
    ('кронштейн бампера', 'kuzov-i-optika', 'kronshteyny-i-krepleniya', 10),
    ('кронштейн салона', 'kuzov-i-optika', 'kronshteyny-i-krepleniya', 10),
    ('скоба фары', 'kuzov-i-optika', 'kronshteyny-i-krepleniya', 10),
    ('насос нож', 'aksessuary', 'nasosy', 4),
    ('насос ручной', 'aksessuary', 'nasosy', 5),
    ('насос электр', 'aksessuary', 'nasosy', 6),
    ('компрессор воздуш', 'aksessuary', 'kompressory', 7),
    ('канистра топлив', 'aksessuary', 'prochie-aksessuary', 8),
    ('ремень безопас', 'aksessuary', 'bezopasnost', 9),
    ('ремня безопасности', 'aksessuary', 'bezopasnost', 9),
    ('ремень крепления', 'aksessuary', 'prochie-aksessuary', 10),
    ('тормозная жидкость', 'filtry-i-masla', 'zhidkosti', 1),
    ('смазка торм', 'filtry-i-masla', 'smazki', 2),
    ('герметик', 'aksessuary', 'avtohimiya', 13),
    ('очистител карб', 'aksessuary', 'avtohimiya', 14),
    ('очистител торм', 'aksessuary', 'avtohimiya', 15),
    ('очистител двиг', 'aksessuary', 'avtohimiya', 16),
    ('очистител стек', 'aksessuary', 'avtohimiya', 17),
    ('очиститель карб', 'aksessuary', 'avtohimiya', 18),
    ('очиститель торм', 'aksessuary', 'avtohimiya', 19),
    ('очиститель двиг', 'aksessuary', 'avtohimiya', 20),
    ('очиститель стек', 'aksessuary', 'avtohimiya', 21),
    ('промывк', 'aksessuary', 'avtohimiya', 15),
    ('присадк', 'aksessuary', 'avtohimiya', 16),
    ('полирол', 'aksessuary', 'avtohimiya', 17),
    ('автошамп', 'aksessuary', 'avtohimiya', 18),
    ('шампун', 'aksessuary', 'avtohimiya', 19),
    ('разморажив', 'aksessuary', 'avtohimiya', 20),
    ('преобразователь ржав', 'aksessuary', 'avtohimiya', 21),
    ('краск', 'aksessuary', 'avtohimiya', 22),
    ('грунт', 'aksessuary', 'avtohimiya', 23),
    ('эмаль', 'aksessuary', 'avtohimiya', 24),
    ('лак', 'aksessuary', 'avtohimiya', 25),
    ('wd-40', 'aksessuary', 'avtohimiya', 27),
    ('головка свеч', 'aksessuary', 'instrumenty', 28),
    ('головка удар', 'aksessuary', 'instrumenty', 29),
    ('головка усиленная', 'aksessuary', 'instrumenty', 30),
    ('головка со встав', 'aksessuary', 'instrumenty', 31),
    ('ключ свеч', 'aksessuary', 'instrumenty', 32),
    ('ключ ступиц', 'aksessuary', 'instrumenty', 33),
    ('ключ торц', 'aksessuary', 'instrumenty', 34),
    ('ключ кардан', 'aksessuary', 'instrumenty', 35),
    ('ключ баллон', 'aksessuary', 'instrumenty', 36),
    ('баллонник', 'aksessuary', 'instrumenty', 37),
    ('набор инструмент', 'aksessuary', 'instrumenty', 38),
    ('съемник', 'aksessuary', 'instrumenty', 39),
    ('съёмник', 'aksessuary', 'instrumenty', 40),
    ('сверло', 'aksessuary', 'instrumenty', 41),
    ('зубило', 'aksessuary', 'instrumenty', 42),
    ('вороток', 'aksessuary', 'instrumenty', 43),
    ('трещотк', 'aksessuary', 'instrumenty', 44),
    ('отвертк', 'aksessuary', 'instrumenty', 45),
    ('пассатиж', 'aksessuary', 'instrumenty', 46),
    ('плоскогуб', 'aksessuary', 'instrumenty', 47),
    ('шприц', 'aksessuary', 'instrumenty', 48),
    ('домкрат', 'aksessuary', 'instrumenty', 49),
    ('зажим свароч', 'aksessuary', 'instrumenty', 50),
    ('а/шина', 'aksessuary', 'shiny-i-diski', 51),
    ('а/шины', 'aksessuary', 'shiny-i-diski', 52),
    ('диск колес', 'aksessuary', 'shiny-i-diski', 53),
    ('колесный диск', 'aksessuary', 'shiny-i-diski', 54),
    ('колпак ступицы', 'aksessuary', 'shiny-i-diski', 55),
    ('колпак колеса', 'aksessuary', 'shiny-i-diski', 56),
    ('гайка колеса', 'aksessuary', 'shiny-i-diski', 57),
    ('болт колеса', 'aksessuary', 'shiny-i-diski', 58),
    ('болт колес', 'aksessuary', 'shiny-i-diski', 58),
    ('шпилька колеса', 'aksessuary', 'shiny-i-diski', 58),
    ('литые диски', 'aksessuary', 'shiny-i-diski', 58),
    ('колпаки для колес', 'aksessuary', 'shiny-i-diski', 58),
    ('колпаки для колёс', 'aksessuary', 'shiny-i-diski', 58),
    ('набор автомобилиста', 'aksessuary', 'bezopasnost', 59),
    ('аптечк', 'aksessuary', 'bezopasnost', 60),
    ('огнетуш', 'aksessuary', 'bezopasnost', 61),
    ('знак авар', 'aksessuary', 'bezopasnost', 62),
    ('трос буксир', 'aksessuary', 'bezopasnost', 63),
    ('буксировочный трос', 'aksessuary', 'bezopasnost', 64),
    ('жилет', 'aksessuary', 'bezopasnost', 65),
    ('книга', 'aksessuary', 'prochie-aksessuary', 66),
    ('каталог', 'aksessuary', 'prochie-aksessuary', 67),
    ('блокнот', 'aksessuary', 'prochie-aksessuary', 68),
    ('наклейк', 'aksessuary', 'prochie-aksessuary', 69),
    ('салфетк', 'aksessuary', 'prochie-aksessuary', 70),
    ('скребок', 'aksessuary', 'prochie-aksessuary', 71),
    ('щетка стеклоочистителя', 'aksessuary', 'prochie-aksessuary', 72),
    ('щётка стеклоочистителя', 'aksessuary', 'prochie-aksessuary', 73),
    ('поводок стеклоочистителя', 'aksessuary', 'prochie-aksessuary', 74),
    ('канистр', 'aksessuary', 'prochie-aksessuary', 75),
    ('воронк', 'aksessuary', 'prochie-aksessuary', 76),
    ('держател', 'aksessuary', 'prochie-aksessuary', 77),
    ('прикуривател', 'aksessuary', 'prochie-aksessuary', 78),
    ('багажник', 'aksessuary', 'prochie-aksessuary', 79),
    ('шторка', 'aksessuary', 'prochie-aksessuary', 80),
    ('оплетка руля', 'aksessuary', 'prochie-aksessuary', 80),
    ('оплётка руля', 'aksessuary', 'prochie-aksessuary', 80),
    ('подлокотник', 'aksessuary', 'prochie-aksessuary', 80),
    ('камера зад', 'aksessuary', 'prochie-aksessuary', 80),
    ('козырек солнцезащит', 'aksessuary', 'prochie-aksessuary', 80),
    ('козырёк солнцезащит', 'aksessuary', 'prochie-aksessuary', 80),
    ('автотепло', 'aksessuary', 'prochie-aksessuary', 81),
    ('автоодеяло', 'aksessuary', 'prochie-aksessuary', 82),
    ('утеплитель двигателя', 'aksessuary', 'prochie-aksessuary', 83),
    ('сигнал воздуш', 'aksessuary', 'prochie-aksessuary', 84),
    ('воздушные сигн', 'aksessuary', 'prochie-aksessuary', 85),
    ('сигналы хром', 'aksessuary', 'prochie-aksessuary', 86),
    ('сигнал хром', 'aksessuary', 'prochie-aksessuary', 87),
    ('прицепное устройство', 'aksessuary', 'prochie-aksessuary', 88),
    ('фаркоп', 'aksessuary', 'prochie-aksessuary', 89),
    ('амортиз', 'podveska', 'amortizatory', 10),
    ('пружин', 'podveska', 'pruzhiny', 20),
    ('рессор', 'podveska', 'ressory', 25),
    ('лист коренной', 'podveska', 'ressory', 26),
    ('лист подкоренной', 'podveska', 'ressory', 27),
    ('стойк', 'podveska', 'stoyki', 30),
    ('опора стоек', 'podveska', 'stoyki', 31),
    ('подшипник', 'podveska', 'podshipniki', 40),
    ('ступица', 'podveska', 'stupicy', 45),
    ('ступицы', 'podveska', 'stupicy', 46),
    ('кулак поворот', 'podveska', 'stupicy', 47),
    ('цапф', 'podveska', 'stupicy', 48),
    ('сайлент', 'podveska', 'saylentbloki', 50),
    ('стабилизатор', 'podveska', 'prochaya-podveska', 52),
    ('втулка стаб', 'podveska', 'prochaya-podveska', 53),
    ('шквор', 'podveska', 'prochaya-podveska', 54),
    ('краб', 'podveska', 'prochaya-podveska', 55),
    ('рычаг', 'podveska', 'rychagi', 60),
    ('шаров', 'podveska', 'sharovye-opory', 70),
    ('кардан рул', 'podveska', 'rulevye-nakonechniki', 75),
    ('рулев', 'podveska', 'rulevye-nakonechniki', 80),
    ('наконечник', 'podveska', 'rulevye-nakonechniki', 90),
    ('аккумулятор', 'elektrika', 'akkumulyatory', 10),
    ('акб', 'elektrika', 'akkumulyatory', 11),
    ('генератор', 'elektrika', 'generatory', 20),
    ('стартер', 'elektrika', 'startery', 30),
    ('ходовые огни', 'elektrika', 'osveshchenie', 35),
    ('дневные ходовые', 'elektrika', 'osveshchenie', 36),
    ('подсветка номера', 'elektrika', 'osveshchenie', 37),
    ('подсветка салона', 'elektrika', 'osveshchenie', 38),
    ('плафон', 'elektrika', 'osveshchenie', 39),
    ('ламп', 'elektrika', 'lampy', 40),
    ('реле', 'elektrika', 'rele', 50),
    ('предохран', 'elektrika', 'predohraniteli', 60),
    ('свечи', 'elektrika', 'svechi-zazhiganiya', 65),
    ('свеча зажиган', 'elektrika', 'svechi-zazhiganiya', 66),
    ('свечами накал', 'elektrika', 'svechi-zazhiganiya', 67),
    ('катушк', 'elektrika', 'prochaya-elektrika', 68),
    ('зажиган', 'elektrika', 'prochaya-elektrika', 69),
    ('датчик', 'elektrika', 'datchiki', 70),
    ('провод', 'elektrika', 'provodka', 80),
    ('колодка-разъем', 'elektrika', 'provodka', 81),
    ('моторчик', 'elektrika', 'prochaya-elektrika', 82),
    ('стеклоподъемник', 'elektrika', 'prochaya-elektrika', 83),
    ('стеклоподъёмник', 'elektrika', 'prochaya-elektrika', 84),
    ('сигнализац', 'elektrika', 'signalizatsii', 85),
    ('автосигнал', 'elektrika', 'signalizatsii', 86),
    ('парктроник', 'elektrika', 'prochaya-elektrika', 87),
    ('бортовой компьютер', 'elektrika', 'prochaya-elektrika', 88),
    ('зарядное устройство', 'elektrika', 'prochaya-elektrika', 89),
    ('масло', 'filtry-i-masla', 'masla', 10),
    ('фильтр масл', 'filtry-i-masla', 'maslyanye-filtry', 15),
    ('масляный фильтр', 'filtry-i-masla', 'maslyanye-filtry', 16),
    ('фильтр воздуш', 'filtry-i-masla', 'vozdushnye-filtry', 20),
    ('воздушный фильтр', 'filtry-i-masla', 'vozdushnye-filtry', 21),
    ('фильтр топлив', 'filtry-i-masla', 'toplivnye-filtry', 30),
    ('топливный фильтр', 'filtry-i-masla', 'toplivnye-filtry', 31),
    ('фильтр салон', 'filtry-i-masla', 'salonnye-filtry', 40),
    ('салонный фильтр', 'filtry-i-masla', 'salonnye-filtry', 41),
    ('фильтр', 'filtry-i-masla', 'maslyanye-filtry', 50),
    ('смазк', 'filtry-i-masla', 'smazki', 60),
    ('антифриз', 'filtry-i-masla', 'zhidkosti', 70),
    ('тосол', 'filtry-i-masla', 'zhidkosti', 71),
    ('жидкость', 'filtry-i-masla', 'zhidkosti', 72),
    ('жидкость гур', 'filtry-i-masla', 'zhidkosti', 73),
    ('жидкость охлажд', 'filtry-i-masla', 'zhidkosti', 74),
    ('тормозн', 'tormoznaya-sistema', 'prochaya-tormoznaya-sistema', 10),
    ('диск торм', 'tormoznaya-sistema', 'tormoznye-diski', 11),
    ('колод', 'tormoznaya-sistema', 'tormoznye-kolodki', 20),
    ('суппорт', 'tormoznaya-sistema', 'supporty', 30),
    ('барабан', 'tormoznaya-sistema', 'barabany', 40),
    ('цилиндр', 'tormoznaya-sistema', 'cilindry', 50),
    ('шланг торм', 'tormoznaya-sistema', 'shlangi', 60),
    ('тормозной шланг', 'tormoznaya-sistema', 'shlangi', 61),
    ('ручник', 'tormoznaya-sistema', 'ruchnoy-tormoz', 62),
    ('ручного торм', 'tormoznaya-sistema', 'ruchnoy-tormoz', 63),
    ('трос руч', 'tormoznaya-sistema', 'ruchnoy-tormoz', 64),
    ('вакуумн усил', 'tormoznaya-sistema', 'prochaya-tormoznaya-sistema', 65),
    ('главный торм', 'tormoznaya-sistema', 'prochaya-tormoznaya-sistema', 66),
    ('регулятор давления тормоз', 'tormoznaya-sistema', 'prochaya-tormoznaya-sistema', 67),
    ('фара', 'kuzov-i-optika', 'fary', 10),
    ('подфарник', 'kuzov-i-optika', 'fary', 11),
    ('очки фар', 'kuzov-i-optika', 'fary', 12),
    ('противотуманки', 'kuzov-i-optika', 'fary', 14),
    ('противотуманные фары', 'kuzov-i-optika', 'fary', 15),
    ('фароискатель', 'kuzov-i-optika', 'fary', 16),
    ('фонар', 'kuzov-i-optika', 'fonari', 20),
    ('зеркал', 'kuzov-i-optika', 'zerkala', 30),
    ('стекло лоб', 'kuzov-i-optika', 'stekla', 31),
    ('стекло ветров', 'kuzov-i-optika', 'stekla', 32),
    ('стекло зад', 'kuzov-i-optika', 'stekla', 33),
    ('стекло бок', 'kuzov-i-optika', 'stekla', 34),
    ('стекло двери', 'kuzov-i-optika', 'stekla', 35),
    ('решет', 'kuzov-i-optika', 'reshetki', 40),
    ('бампер', 'kuzov-i-optika', 'bampery', 50),
    ('молдинг', 'kuzov-i-optika', 'moldingi', 60),
    ('брызговик', 'kuzov-i-optika', 'podkrylki-i-bryzgoviki', 61),
    ('подкрыл', 'kuzov-i-optika', 'podkrylki-i-bryzgoviki', 62),
    ('арка крыла', 'kuzov-i-optika', 'podkrylki-i-bryzgoviki', 63),
    ('замок багажника', 'kuzov-i-optika', 'zamki-i-ruchki', 64),
    ('замок двер', 'kuzov-i-optika', 'zamki-i-ruchki', 65),
    ('ручка двер', 'kuzov-i-optika', 'zamki-i-ruchki', 66),
    ('ручки двер', 'kuzov-i-optika', 'zamki-i-ruchki', 67),
    ('ручка стеклопод', 'kuzov-i-optika', 'zamki-i-ruchki', 68),
    ('личинк', 'kuzov-i-optika', 'zamki-i-ruchki', 69),
    ('крышка бака', 'kuzov-i-optika', 'zamki-i-ruchki', 70),
    ('двер', 'kuzov-i-optika', 'kuzovnye-detali', 70),
    ('крыло', 'kuzov-i-optika', 'kuzovnye-detali', 71),
    ('капот', 'kuzov-i-optika', 'kuzovnye-detali', 72),
    ('панель', 'kuzov-i-optika', 'kuzovnye-detali', 73),
    ('дефлектор', 'kuzov-i-optika', 'obves-i-dekor', 74),
    ('ветровик', 'kuzov-i-optika', 'obves-i-dekor', 75),
    ('спойлер', 'kuzov-i-optika', 'obves-i-dekor', 76),
    ('порог', 'kuzov-i-optika', 'kuzovnye-detali', 77),
    ('порожк', 'kuzov-i-optika', 'kuzovnye-detali', 78),
    ('ремень', 'dvigatel-i-transmissiya', 'remni', 10),
    ('грм', 'dvigatel-i-transmissiya', 'remni', 11),
    ('ремня грм', 'dvigatel-i-transmissiya', 'remni', 12),
    ('проклад', 'dvigatel-i-transmissiya', 'prokladki', 20),
    ('насос', 'dvigatel-i-transmissiya', 'nasosy', 30),
    ('помп', 'dvigatel-i-transmissiya', 'nasosy', 31),
    ('сцеплен', 'dvigatel-i-transmissiya', 'sceplenie', 40),
    ('пгу', 'dvigatel-i-transmissiya', 'sceplenie', 41),
    ('выжимной', 'dvigatel-i-transmissiya', 'sceplenie', 42),
    ('муфта выжимная', 'dvigatel-i-transmissiya', 'sceplenie', 43),
    ('графитка выжим', 'dvigatel-i-transmissiya', 'sceplenie', 44),
    ('кпп', 'dvigatel-i-transmissiya', 'kpp', 50),
    ('коробка передач', 'dvigatel-i-transmissiya', 'kpp', 51),
    ('шток выбора передач', 'dvigatel-i-transmissiya', 'kpp', 52),
    ('кулиса', 'dvigatel-i-transmissiya', 'kpp', 53),
    ('ремкомплект коробки', 'dvigatel-i-transmissiya', 'kpp', 54),
    ('рем комплект коробки', 'dvigatel-i-transmissiya', 'kpp', 55),
    ('вилка коробки', 'dvigatel-i-transmissiya', 'kpp', 56),
    ('вал вторичный', 'dvigatel-i-transmissiya', 'kpp', 57),
    ('первичный вал', 'dvigatel-i-transmissiya', 'kpp', 58),
    ('ролик натяжного', 'dvigatel-i-transmissiya', 'remni', 59),
    ('ролик поликлинов', 'dvigatel-i-transmissiya', 'remni', 59),
    ('двигател', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 60),
    ('порш', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 61),
    ('сальник', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 62),
    ('головка блока', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 63),
    ('гбц', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 64),
    ('головки блока', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 64),
    ('болт головки', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 64),
    ('шпилька головки', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 64),
    ('вал коленчат', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 64),
    ('клапана', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 64),
    ('распредвал', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 65),
    ('коленвал', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 66),
    ('кол. вала', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 67),
    ('шкив кол', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 68),
    ('клапан голов', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 69),
    ('трансмисс', 'dvigatel-i-transmissiya', 'detali-transmissii', 70),
    ('шрус', 'dvigatel-i-transmissiya', 'detali-transmissii', 71),
    ('кардан', 'dvigatel-i-transmissiya', 'detali-transmissii', 72),
    ('полуос', 'dvigatel-i-transmissiya', 'detali-transmissii', 73),
    ('редуктор', 'dvigatel-i-transmissiya', 'detali-transmissii', 74),
    ('раздатк', 'dvigatel-i-transmissiya', 'detali-transmissii', 75),
    ('шарнир наружный', 'dvigatel-i-transmissiya', 'detali-transmissii', 76),
    ('привод спидометра', 'dvigatel-i-transmissiya', 'detali-transmissii', 77),
    ('шестерня заднего хода', 'dvigatel-i-transmissiya', 'detali-transmissii', 78),
    ('блок шестер', 'dvigatel-i-transmissiya', 'detali-transmissii', 79),
    ('задний мост', 'dvigatel-i-transmissiya', 'detali-transmissii', 79),
    ('заднего моста', 'dvigatel-i-transmissiya', 'detali-transmissii', 79),
    ('чулок заднего моста', 'dvigatel-i-transmissiya', 'detali-transmissii', 79),
    ('муфта подвесная', 'dvigatel-i-transmissiya', 'detali-transmissii', 79),
    ('крестовина кард', 'dvigatel-i-transmissiya', 'detali-transmissii', 79),
    ('кард. вала', 'dvigatel-i-transmissiya', 'detali-transmissii', 79),
    ('кард.вала', 'dvigatel-i-transmissiya', 'detali-transmissii', 79),
    ('радиатор', 'dvigatel-i-transmissiya', 'ohlazhdenie', 80),
    ('термостат', 'dvigatel-i-transmissiya', 'ohlazhdenie', 81),
    ('расширительного бачка', 'dvigatel-i-transmissiya', 'ohlazhdenie', 84),
    ('бачок расширительный', 'dvigatel-i-transmissiya', 'ohlazhdenie', 84),
    ('вентилятор радиатора', 'dvigatel-i-transmissiya', 'ohlazhdenie', 85),
    ('вентилятор охлажд', 'dvigatel-i-transmissiya', 'ohlazhdenie', 86),
    ('карбюратор', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 87),
    ('дроссель', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 88),
    ('бензонасос', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 89),
    ('бензобак', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 90),
    ('бак топлив', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 91),
    ('топливный бак', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 92),
    ('глушител', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 93),
    ('резонатор', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 94),
    ('приемная труба', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 95),
    ('приёмная труба', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 96),
    ('труба приемная', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 96),
    ('труба приёмная', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 96),
    ('труба выхлоп', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 97),
    ('труба выпуск', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 97),
    ('труба промежуточ', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 97),
    ('катализатор', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 98),
    ('гофра глуш', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 99),
    ('гофра трехслой', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 99),
    ('гофра трёхслой', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 99),
    ('хомут глуш', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 100),
    ('система выпуска', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 101),
    ('коллектор выпуск', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 102),
    ('металлорукав', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 103),
    ('металорукав', 'dvigatel-i-transmissiya', 'vyhlopnaya-sistema', 104),
    ('трос газа', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 105),
    ('педаль газа', 'dvigatel-i-transmissiya', 'toplivnaya-sistema', 106),
    ('чехол', 'aksessuary', 'chehly', 10),
    ('чехлы', 'aksessuary', 'chehly', 11),
    ('коврик', 'aksessuary', 'kovriki', 20),
    ('ковры', 'aksessuary', 'kovriki', 21),
    ('компрессор', 'aksessuary', 'kompressory', 30),
    ('рамк', 'aksessuary', 'ramki-nomerov', 50),
    ('автохим', 'aksessuary', 'avtohimiya', 60),
    ('органайзер', 'aksessuary', 'organayzery', 70),
    ('дворник', 'aksessuary', 'prochie-aksessuary', 80),
    ('антенн', 'aksessuary', 'prochie-aksessuary', 81),
    ('и-', 'aksessuary', 'instrumenty', 190),
    ('ш-', 'aksessuary', 'shiny-i-diski', 191),
    ('д-', 'aksessuary', 'shiny-i-diski', 192),
    ('двг-', 'dvigatel-i-transmissiya', 'detali-dvigatelya', 200),
    ('кп-', 'dvigatel-i-transmissiya', 'kpp', 210),
    ('зкг-', 'dvigatel-i-transmissiya', 'detali-transmissii', 211),
    ('сц-', 'dvigatel-i-transmissiya', 'sceplenie', 212),
    ('сцг-', 'dvigatel-i-transmissiya', 'sceplenie', 213),
    ('ре-', 'podveska', 'ressory', 214),
    ('эо-', 'elektrika', 'prochaya-elektrika', 220),
    ('эог-', 'elektrika', 'prochaya-elektrika', 221),
    ('гсм-', 'filtry-i-masla', 'zhidkosti', 230),
    ('тс-', 'tormoznaya-sistema', 'prochaya-tormoznaya-sistema', 240),
    ('тсг-', 'tormoznaya-sistema', 'prochaya-tormoznaya-sistema', 241),
    ('ж-', 'kuzov-i-optika', 'kuzovnye-detali', 250),
    ('жл-', 'kuzov-i-optika', 'kuzovnye-detali', 251),
    ('кз-', 'kuzov-i-optika', 'kuzovnye-detali', 252)
)
INSERT INTO categorization_rules (pattern, match_type, category_id, subcategory_id, priority)
SELECT
  rule_seed.pattern,
  'contains',
  categories.id,
  subcategories.id,
  rule_seed.priority
FROM rule_seed
JOIN categories ON categories.slug = rule_seed.category_slug
JOIN subcategories
  ON subcategories.category_id = categories.id
 AND subcategories.slug = rule_seed.subcategory_slug
ON CONFLICT (pattern, match_type, category_id, subcategory_id) DO UPDATE
SET
  priority = EXCLUDED.priority,
  is_active = true,
  updated_at = now();

WITH deprecated_rule_seed(pattern, match_type, category_slug, subcategory_slug) AS (
  VALUES
    ('воздушн', 'contains', NULL, NULL),
    ('топлив', 'contains', NULL, NULL),
    ('салон', 'contains', NULL, NULL),
    ('шланг', 'contains', NULL, NULL),
    ('патрубок радиатор', 'contains', 'dvigatel-i-transmissiya', 'ohlazhdenie'),
    ('патрубки печки', 'contains', 'dvigatel-i-transmissiya', 'ohlazhdenie'),
    ('стекло фары', 'contains', 'kuzov-i-optika', 'fary'),
    ('стекло фар', 'contains', 'kuzov-i-optika', 'fary')
)
UPDATE categorization_rules
SET
  is_active = false,
  updated_at = now()
FROM deprecated_rule_seed
LEFT JOIN categories
  ON categories.slug = deprecated_rule_seed.category_slug
LEFT JOIN subcategories
  ON subcategories.category_id = categories.id
 AND subcategories.slug = deprecated_rule_seed.subcategory_slug
WHERE
  categorization_rules.created_by IS NULL
  AND categorization_rules.pattern = deprecated_rule_seed.pattern
  AND categorization_rules.match_type = deprecated_rule_seed.match_type::rule_match_type
  AND (
    deprecated_rule_seed.category_slug IS NULL
    OR (
      categorization_rules.category_id = categories.id
      AND categorization_rules.subcategory_id = subcategories.id
    )
  );
