import { catalogCategories } from "./categories";

export type CatalogTaxonomyCategory = (typeof catalogTaxonomy)[number];
export type CatalogTaxonomySubcategory = CatalogTaxonomyCategory["subcategories"][number];
export type DefaultCategorizationRule = (typeof defaultCategorizationRules)[number];

export const catalogTaxonomy = [
  {
    slug: "podveska",
    name: "Подвеска",
    subcategories: [
      ["amortizatory", "Амортизаторы"],
      ["pruzhiny", "Пружины"],
      ["ressory", "Рессоры"],
      ["stoyki", "Стойки"],
      ["podshipniki", "Подшипники"],
      ["stupicy", "Ступицы и кулаки"],
      ["saylentbloki", "Сайлентблоки"],
      ["rychagi", "Рычаги"],
      ["sharovye-opory", "Шаровые опоры"],
      ["rulevye-nakonechniki", "Рулевые наконечники"],
      ["rulevye-tyagi", "Рулевые тяги"],
      ["shlangi-gur", "Шланги ГУР"],
      ["remkomplekty-gur", "Ремкомплекты ГУР"],
      ["prochaya-podveska", "Прочая подвеска"]
    ]
  },
  {
    slug: "elektrika",
    name: "Электрика",
    subcategories: [
      ["akkumulyatory", "Аккумуляторы"],
      ["generatory", "Генераторы"],
      ["startery", "Стартеры"],
      ["lampy", "Лампы"],
      ["osveshchenie", "Освещение"],
      ["rele", "Реле"],
      ["predohraniteli", "Предохранители"],
      ["datchiki", "Датчики"],
      ["provodka", "Проводка"],
      ["svechi-zazhiganiya", "Свечи зажигания"],
      ["signalizatsii", "Сигнализации"],
      ["prochaya-elektrika", "Прочая электрика"]
    ]
  },
  {
    slug: "filtry-i-masla",
    name: "Фильтры и масла",
    subcategories: [
      ["masla", "Масла"],
      ["maslyanye-filtry", "Масляные фильтры"],
      ["vozdushnye-filtry", "Воздушные фильтры"],
      ["toplivnye-filtry", "Топливные фильтры"],
      ["salonnye-filtry", "Салонные фильтры"],
      ["smazki", "Смазки"],
      ["zhidkosti", "Технические жидкости"]
    ]
  },
  {
    slug: "tormoznaya-sistema",
    name: "Тормозная система",
    subcategories: [
      ["tormoznye-diski", "Тормозные диски"],
      ["tormoznye-kolodki", "Тормозные колодки"],
      ["supporty", "Суппорты"],
      ["barabany", "Барабаны"],
      ["cilindry", "Цилиндры"],
      ["shlangi", "Шланги"],
      ["tormoznye-trubki", "Тормозные трубки"],
      ["remkomplekty-tormoznoy-sistemy", "Ремкомплекты тормозной системы"],
      ["tormoznye-shtucery", "Тормозные штуцеры"],
      ["ruchnoy-tormoz", "Ручной тормоз"],
      ["prochaya-tormoznaya-sistema", "Прочая тормозная система"]
    ]
  },
  {
    slug: "kuzov-i-optika",
    name: "Кузов и оптика",
    subcategories: [
      ["fary", "Фары"],
      ["fonari", "Фонари"],
      ["zerkala", "Зеркала"],
      ["stekla", "Стекла"],
      ["reshetki", "Решетки"],
      ["bampery", "Бамперы"],
      ["moldingi", "Молдинги"],
      ["podkrylki-i-bryzgoviki", "Подкрылки и брызговики"],
      ["zamki-i-ruchki", "Замки и ручки"],
      ["obves-i-dekor", "Обвес и декор"],
      ["elementy-salona", "Элементы салона"],
      ["emblemy", "Эмблемы"],
      ["povtoriteli", "Повторители"],
      ["stekla-far-i-fonarey", "Стёкла фар и фонарей"],
      ["kryshki-i-korpusa-optiki", "Крышки и корпуса оптики"],
      ["kronshteyny-i-krepleniya", "Кронштейны и крепления"],
      ["kuzovnye-detali", "Кузовные детали"]
    ]
  },
  {
    slug: "dvigatel-i-transmissiya",
    name: "Двигатель и трансмиссия",
    subcategories: [
      ["remni", "Ремни"],
      ["prokladki", "Прокладки"],
      ["nasosy", "Насосы"],
      ["sceplenie", "Сцепление"],
      ["kpp", "КПП"],
      ["ohlazhdenie", "Охлаждение"],
      ["patrubki-i-shlangi-ohlazhdeniya", "Патрубки и шланги охлаждения"],
      ["homuty-ohlazhdeniya", "Хомуты охлаждения"],
      ["kryshki-i-probki-ohlazhdeniya", "Крышки и пробки охлаждения"],
      ["toplivnaya-sistema", "Топливная система"],
      ["vyhlopnaya-sistema", "Выхлопная система"],
      ["detali-dvigatelya", "Детали двигателя"],
      ["detali-transmissii", "Детали трансмиссии"]
    ]
  },
  {
    slug: "krepezh",
    name: "Крепёж",
    subcategories: [
      ["bolty", "Болты"],
      ["gayki", "Гайки"],
      ["shayby", "Шайбы"],
      ["shpilki", "Шпильки"],
      ["vinty", "Винты"],
      ["homuty", "Хомуты"],
      ["koltsa", "Кольца"],
      ["skoby-i-kronshteyny", "Скобы и кронштейны"],
      ["shtucery-i-fitingi", "Штуцеры и фитинги"],
      ["soediniteli", "Соединители"]
    ]
  },
  {
    slug: "aksessuary",
    name: "Аксессуары",
    subcategories: [
      ["chehly", "Чехлы"],
      ["kovriki", "Коврики"],
      ["kompressory", "Компрессоры"],
      ["nasosy", "Насосы"],
      ["instrumenty", "Инструменты"],
      ["shiny-i-diski", "Шины и диски"],
      ["ramki-nomerov", "Рамки номеров"],
      ["avtohimiya", "Автохимия"],
      ["organayzery", "Органайзеры"],
      ["bezopasnost", "Безопасность"],
      ["prochie-aksessuary", "Прочие аксессуары"]
    ]
  },
  {
    slug: "ves-assortiment",
    name: "Весь ассортимент",
    subcategories: [["vse-tovary", "Все товары"]]
  }
] as const;

export const categoryBySlug = new Map(catalogCategories.map((category) => [category.slug, category]));

export const defaultCategorizationRules = [
  rule("трубка торм", "tormoznaya-sistema", "tormoznye-trubki", 3),
  rule("тормозная трубка", "tormoznaya-sistema", "tormoznye-trubki", 3),
  rule("трубки торм", "tormoznaya-sistema", "tormoznye-trubki", 3),
  rule("штуцер торм", "tormoznaya-sistema", "tormoznye-shtucery", 4),
  rule("штуцер прокач", "tormoznaya-sistema", "tormoznye-shtucery", 4),
  rule("тройник торм", "tormoznaya-sistema", "tormoznye-shtucery", 4),
  rule("ремкомплект суппорт", "tormoznaya-sistema", "remkomplekty-tormoznoy-sistemy", 5),
  rule("ремкомплект торм", "tormoznaya-sistema", "remkomplekty-tormoznoy-sistemy", 5),
  rule("рем комплект торм", "tormoznaya-sistema", "remkomplekty-tormoznoy-sistemy", 5),
  rule("рем. к-т торм", "tormoznaya-sistema", "remkomplekty-tormoznoy-sistemy", 5),
  rule("рем к-т торм", "tormoznaya-sistema", "remkomplekty-tormoznoy-sistemy", 5),
  rule("ремкомплект цилиндра торм", "tormoznaya-sistema", "remkomplekty-tormoznoy-sistemy", 5),
  rule("ремкомплект главного торм", "tormoznaya-sistema", "remkomplekty-tormoznoy-sistemy", 5),
  rule("шланг гур", "podveska", "shlangi-gur", 6),
  rule("шланг гура", "podveska", "shlangi-gur", 6),
  rule("трубка гур", "podveska", "shlangi-gur", 6),
  rule("ремкомплект гур", "podveska", "remkomplekty-gur", 7),
  rule("ремкомплект гура", "podveska", "remkomplekty-gur", 7),
  rule("рем комплект гур", "podveska", "remkomplekty-gur", 7),
  rule("рем. к-т гур", "podveska", "remkomplekty-gur", 7),
  rule("рем к-т гур", "podveska", "remkomplekty-gur", 7),
  rule("ремкомплект рулевой рейки", "podveska", "remkomplekty-gur", 7),
  rule("рулевая тяга", "podveska", "rulevye-tyagi", 8),
  rule("тяга рул", "podveska", "rulevye-tyagi", 8),
  rule("патрубок радиатор", "dvigatel-i-transmissiya", "patrubki-i-shlangi-ohlazhdeniya", 8),
  rule("патрубок охлажд", "dvigatel-i-transmissiya", "patrubki-i-shlangi-ohlazhdeniya", 8),
  rule("патрубки охлажд", "dvigatel-i-transmissiya", "patrubki-i-shlangi-ohlazhdeniya", 8),
  rule("патрубок отопител", "dvigatel-i-transmissiya", "patrubki-i-shlangi-ohlazhdeniya", 8),
  rule("патрубки печки", "dvigatel-i-transmissiya", "patrubki-i-shlangi-ohlazhdeniya", 8),
  rule("шланг радиатор", "dvigatel-i-transmissiya", "patrubki-i-shlangi-ohlazhdeniya", 8),
  rule("шланг охлажд", "dvigatel-i-transmissiya", "patrubki-i-shlangi-ohlazhdeniya", 8),
  rule("тройник радиатор", "dvigatel-i-transmissiya", "patrubki-i-shlangi-ohlazhdeniya", 8),
  rule("тройник охлажд", "dvigatel-i-transmissiya", "patrubki-i-shlangi-ohlazhdeniya", 8),
  rule("хомут радиатор", "dvigatel-i-transmissiya", "homuty-ohlazhdeniya", 9),
  rule("хомут патруб", "dvigatel-i-transmissiya", "homuty-ohlazhdeniya", 9),
  rule("хомут охлажд", "dvigatel-i-transmissiya", "homuty-ohlazhdeniya", 9),
  rule("крышка радиатор", "dvigatel-i-transmissiya", "kryshki-i-probki-ohlazhdeniya", 9),
  rule("крышка расширител", "dvigatel-i-transmissiya", "kryshki-i-probki-ohlazhdeniya", 9),
  rule("крышка бачка охлажд", "dvigatel-i-transmissiya", "kryshki-i-probki-ohlazhdeniya", 9),
  rule("крышка бачка расшир", "dvigatel-i-transmissiya", "kryshki-i-probki-ohlazhdeniya", 9),
  rule("пробка радиатор", "dvigatel-i-transmissiya", "kryshki-i-probki-ohlazhdeniya", 9),
  rule("пробка расширител", "dvigatel-i-transmissiya", "kryshki-i-probki-ohlazhdeniya", 9),
  rule("пробка бачка охлажд", "dvigatel-i-transmissiya", "kryshki-i-probki-ohlazhdeniya", 9),
  rule("пробка бачка расшир", "dvigatel-i-transmissiya", "kryshki-i-probki-ohlazhdeniya", 9),
  rule("крышка бардач", "kuzov-i-optika", "elementy-salona", 9),
  rule("крышка трамблер", "elektrika", "prochaya-elektrika", 9),
  rule("крышка трамблера", "elektrika", "prochaya-elektrika", 9),
  rule("крышка распределителя", "elektrika", "prochaya-elektrika", 9),
  rule("крышка гбц", "dvigatel-i-transmissiya", "detali-dvigatelya", 9),
  rule("крышка клапан", "dvigatel-i-transmissiya", "detali-dvigatelya", 9),
  rule("клапанная крышка", "dvigatel-i-transmissiya", "detali-dvigatelya", 9),
  rule("ремкомплект карбюратор", "dvigatel-i-transmissiya", "toplivnaya-sistema", 9),
  rule("рем комплект карбюратор", "dvigatel-i-transmissiya", "toplivnaya-sistema", 9),
  rule("шланг топлив", "dvigatel-i-transmissiya", "toplivnaya-sistema", 9),
  rule("трубка топлив", "dvigatel-i-transmissiya", "toplivnaya-sistema", 9),
  rule("кольцо поршн", "dvigatel-i-transmissiya", "detali-dvigatelya", 9),
  rule("кольца поршн", "dvigatel-i-transmissiya", "detali-dvigatelya", 9),
  rule("кольцо синхронизатор", "dvigatel-i-transmissiya", "detali-transmissii", 9),
  rule("стекло фары", "kuzov-i-optika", "stekla-far-i-fonarey", 9),
  rule("стекло фар", "kuzov-i-optika", "stekla-far-i-fonarey", 9),
  rule("стекло фонаря", "kuzov-i-optika", "stekla-far-i-fonarey", 9),
  rule("стекло фонар", "kuzov-i-optika", "stekla-far-i-fonarey", 9),
  rule("корпус фары", "kuzov-i-optika", "kryshki-i-korpusa-optiki", 9),
  rule("корпус фонаря", "kuzov-i-optika", "kryshki-i-korpusa-optiki", 9),
  rule("крышка фары", "kuzov-i-optika", "kryshki-i-korpusa-optiki", 9),
  rule("крышка фонаря", "kuzov-i-optika", "kryshki-i-korpusa-optiki", 9),
  rule("повторитель", "kuzov-i-optika", "povtoriteli", 9),
  rule("поворотник", "kuzov-i-optika", "povtoriteli", 9),
  rule("указатель поворота", "kuzov-i-optika", "povtoriteli", 9),
  rule("эмблема", "kuzov-i-optika", "emblemy", 9),
  rule("шильдик", "kuzov-i-optika", "emblemy", 9),
  rule("знак", "kuzov-i-optika", "emblemy", 130),
  rule("кронштейн фары", "kuzov-i-optika", "kronshteyny-i-krepleniya", 10),
  rule("кронштейн бампера", "kuzov-i-optika", "kronshteyny-i-krepleniya", 10),
  rule("кронштейн салона", "kuzov-i-optika", "kronshteyny-i-krepleniya", 10),
  rule("скоба фары", "kuzov-i-optika", "kronshteyny-i-krepleniya", 10),

  rule("насос нож", "aksessuary", "nasosy", 4),
  rule("насос ручной", "aksessuary", "nasosy", 5),
  rule("насос электр", "aksessuary", "nasosy", 6),
  rule("компрессор воздуш", "aksessuary", "kompressory", 7),
  rule("канистра топлив", "aksessuary", "prochie-aksessuary", 8),
  rule("ремень безопас", "aksessuary", "bezopasnost", 9),
  rule("ремня безопасности", "aksessuary", "bezopasnost", 9),
  rule("ремень крепления", "aksessuary", "prochie-aksessuary", 10),
  rule("тормозная жидкость", "filtry-i-masla", "zhidkosti", 1),
  rule("смазка торм", "filtry-i-masla", "smazki", 2),
  rule("герметик", "aksessuary", "avtohimiya", 13),
  rule("очистител карб", "aksessuary", "avtohimiya", 14),
  rule("очистител торм", "aksessuary", "avtohimiya", 15),
  rule("очистител двиг", "aksessuary", "avtohimiya", 16),
  rule("очистител стек", "aksessuary", "avtohimiya", 17),
  rule("очиститель карб", "aksessuary", "avtohimiya", 18),
  rule("очиститель торм", "aksessuary", "avtohimiya", 19),
  rule("очиститель двиг", "aksessuary", "avtohimiya", 20),
  rule("очиститель стек", "aksessuary", "avtohimiya", 21),
  rule("промывк", "aksessuary", "avtohimiya", 15),
  rule("присадк", "aksessuary", "avtohimiya", 16),
  rule("полирол", "aksessuary", "avtohimiya", 17),
  rule("автошамп", "aksessuary", "avtohimiya", 18),
  rule("шампун", "aksessuary", "avtohimiya", 19),
  rule("разморажив", "aksessuary", "avtohimiya", 20),
  rule("преобразователь ржав", "aksessuary", "avtohimiya", 21),
  rule("краск", "aksessuary", "avtohimiya", 22),
  rule("грунт", "aksessuary", "avtohimiya", 23),
  rule("эмаль", "aksessuary", "avtohimiya", 24),
  rule("лак", "aksessuary", "avtohimiya", 25),
  rule("wd-40", "aksessuary", "avtohimiya", 27),
  rule("головка свеч", "aksessuary", "instrumenty", 28),
  rule("головка удар", "aksessuary", "instrumenty", 29),
  rule("головка усиленная", "aksessuary", "instrumenty", 30),
  rule("головка со встав", "aksessuary", "instrumenty", 31),
  rule("ключ свеч", "aksessuary", "instrumenty", 32),
  rule("ключ ступиц", "aksessuary", "instrumenty", 33),
  rule("ключ торц", "aksessuary", "instrumenty", 34),
  rule("ключ кардан", "aksessuary", "instrumenty", 35),
  rule("ключ баллон", "aksessuary", "instrumenty", 36),
  rule("баллонник", "aksessuary", "instrumenty", 37),
  rule("набор инструмент", "aksessuary", "instrumenty", 38),
  rule("съемник", "aksessuary", "instrumenty", 39),
  rule("съёмник", "aksessuary", "instrumenty", 40),
  rule("сверло", "aksessuary", "instrumenty", 41),
  rule("зубило", "aksessuary", "instrumenty", 42),
  rule("вороток", "aksessuary", "instrumenty", 43),
  rule("трещотк", "aksessuary", "instrumenty", 44),
  rule("отвертк", "aksessuary", "instrumenty", 45),
  rule("пассатиж", "aksessuary", "instrumenty", 46),
  rule("плоскогуб", "aksessuary", "instrumenty", 47),
  rule("шприц", "aksessuary", "instrumenty", 48),
  rule("домкрат", "aksessuary", "instrumenty", 49),
  rule("зажим свароч", "aksessuary", "instrumenty", 50),
  rule("а/шина", "aksessuary", "shiny-i-diski", 51),
  rule("а/шины", "aksessuary", "shiny-i-diski", 52),
  rule("диск колес", "aksessuary", "shiny-i-diski", 53),
  rule("колесный диск", "aksessuary", "shiny-i-diski", 54),
  rule("колпак ступицы", "aksessuary", "shiny-i-diski", 55),
  rule("колпак колеса", "aksessuary", "shiny-i-diski", 56),
  rule("гайка колеса", "aksessuary", "shiny-i-diski", 57),
  rule("болт колеса", "aksessuary", "shiny-i-diski", 58),
  rule("болт колес", "aksessuary", "shiny-i-diski", 58),
  rule("шпилька колеса", "aksessuary", "shiny-i-diski", 58),
  rule("литые диски", "aksessuary", "shiny-i-diski", 58),
  rule("колпаки для колес", "aksessuary", "shiny-i-diski", 58),
  rule("колпаки для колёс", "aksessuary", "shiny-i-diski", 58),
  rule("набор автомобилиста", "aksessuary", "bezopasnost", 59),
  rule("аптечк", "aksessuary", "bezopasnost", 60),
  rule("огнетуш", "aksessuary", "bezopasnost", 61),
  rule("знак авар", "aksessuary", "bezopasnost", 62),
  rule("трос буксир", "aksessuary", "bezopasnost", 63),
  rule("буксировочный трос", "aksessuary", "bezopasnost", 64),
  rule("жилет", "aksessuary", "bezopasnost", 65),
  rule("книга", "aksessuary", "prochie-aksessuary", 66),
  rule("каталог", "aksessuary", "prochie-aksessuary", 67),
  rule("блокнот", "aksessuary", "prochie-aksessuary", 68),
  rule("наклейк", "aksessuary", "prochie-aksessuary", 69),
  rule("салфетк", "aksessuary", "prochie-aksessuary", 70),
  rule("скребок", "aksessuary", "prochie-aksessuary", 71),
  rule("щетка стеклоочистителя", "aksessuary", "prochie-aksessuary", 72),
  rule("щётка стеклоочистителя", "aksessuary", "prochie-aksessuary", 73),
  rule("поводок стеклоочистителя", "aksessuary", "prochie-aksessuary", 74),
  rule("канистр", "aksessuary", "prochie-aksessuary", 75),
  rule("воронк", "aksessuary", "prochie-aksessuary", 76),
  rule("держател", "aksessuary", "prochie-aksessuary", 77),
  rule("прикуривател", "aksessuary", "prochie-aksessuary", 78),
  rule("багажник", "aksessuary", "prochie-aksessuary", 79),
  rule("шторка", "aksessuary", "prochie-aksessuary", 80),
  rule("оплетка руля", "aksessuary", "prochie-aksessuary", 80),
  rule("оплётка руля", "aksessuary", "prochie-aksessuary", 80),
  rule("подлокотник", "aksessuary", "prochie-aksessuary", 80),
  rule("камера зад", "aksessuary", "prochie-aksessuary", 80),
  rule("козырек солнцезащит", "aksessuary", "prochie-aksessuary", 80),
  rule("козырёк солнцезащит", "aksessuary", "prochie-aksessuary", 80),
  rule("автотепло", "aksessuary", "prochie-aksessuary", 81),
  rule("автоодеяло", "aksessuary", "prochie-aksessuary", 82),
  rule("утеплитель двигателя", "aksessuary", "prochie-aksessuary", 83),
  rule("сигнал воздуш", "aksessuary", "prochie-aksessuary", 84),
  rule("воздушные сигн", "aksessuary", "prochie-aksessuary", 85),
  rule("сигналы хром", "aksessuary", "prochie-aksessuary", 86),
  rule("сигнал хром", "aksessuary", "prochie-aksessuary", 87),
  rule("прицепное устройство", "aksessuary", "prochie-aksessuary", 88),
  rule("фаркоп", "aksessuary", "prochie-aksessuary", 89),

  rule("амортиз", "podveska", "amortizatory", 10),
  rule("пружин", "podveska", "pruzhiny", 20),
  rule("рессор", "podveska", "ressory", 25),
  rule("лист коренной", "podveska", "ressory", 26),
  rule("лист подкоренной", "podveska", "ressory", 27),
  rule("стойк", "podveska", "stoyki", 30),
  rule("опора стоек", "podveska", "stoyki", 31),
  rule("подшипник", "podveska", "podshipniki", 40),
  rule("ступица", "podveska", "stupicy", 45),
  rule("ступицы", "podveska", "stupicy", 46),
  rule("кулак поворот", "podveska", "stupicy", 47),
  rule("цапф", "podveska", "stupicy", 48),
  rule("сайлент", "podveska", "saylentbloki", 50),
  rule("стабилизатор", "podveska", "prochaya-podveska", 52),
  rule("втулка стаб", "podveska", "prochaya-podveska", 53),
  rule("шквор", "podveska", "prochaya-podveska", 54),
  rule("краб", "podveska", "prochaya-podveska", 55),
  rule("рычаг", "podveska", "rychagi", 60),
  rule("шаров", "podveska", "sharovye-opory", 70),
  rule("кардан рул", "podveska", "rulevye-nakonechniki", 75),
  rule("рулев", "podveska", "rulevye-nakonechniki", 80),
  rule("наконечник", "podveska", "rulevye-nakonechniki", 90),

  rule("аккумулятор", "elektrika", "akkumulyatory", 10),
  rule("акб", "elektrika", "akkumulyatory", 11),
  rule("генератор", "elektrika", "generatory", 20),
  rule("стартер", "elektrika", "startery", 30),
  rule("ходовые огни", "elektrika", "osveshchenie", 35),
  rule("дневные ходовые", "elektrika", "osveshchenie", 36),
  rule("подсветка номера", "elektrika", "osveshchenie", 37),
  rule("подсветка салона", "elektrika", "osveshchenie", 38),
  rule("плафон", "elektrika", "osveshchenie", 39),
  rule("ламп", "elektrika", "lampy", 40),
  rule("реле", "elektrika", "rele", 50),
  rule("предохран", "elektrika", "predohraniteli", 60),
  rule("свечи", "elektrika", "svechi-zazhiganiya", 65),
  rule("свеча зажиган", "elektrika", "svechi-zazhiganiya", 66),
  rule("свечами накал", "elektrika", "svechi-zazhiganiya", 67),
  rule("катушк", "elektrika", "prochaya-elektrika", 68),
  rule("зажиган", "elektrika", "prochaya-elektrika", 69),
  rule("датчик", "elektrika", "datchiki", 70),
  rule("провод", "elektrika", "provodka", 80),
  rule("колодка-разъем", "elektrika", "provodka", 81),
  rule("моторчик", "elektrika", "prochaya-elektrika", 82),
  rule("стеклоподъемник", "elektrika", "prochaya-elektrika", 83),
  rule("стеклоподъёмник", "elektrika", "prochaya-elektrika", 84),
  rule("сигнализац", "elektrika", "signalizatsii", 85),
  rule("автосигнал", "elektrika", "signalizatsii", 86),
  rule("парктроник", "elektrika", "prochaya-elektrika", 87),
  rule("бортовой компьютер", "elektrika", "prochaya-elektrika", 88),
  rule("зарядное устройство", "elektrika", "prochaya-elektrika", 89),

  rule("масло", "filtry-i-masla", "masla", 10),
  rule("фильтр масл", "filtry-i-masla", "maslyanye-filtry", 15),
  rule("масляный фильтр", "filtry-i-masla", "maslyanye-filtry", 16),
  rule("фильтр воздуш", "filtry-i-masla", "vozdushnye-filtry", 20),
  rule("воздушный фильтр", "filtry-i-masla", "vozdushnye-filtry", 21),
  rule("фильтр топлив", "filtry-i-masla", "toplivnye-filtry", 30),
  rule("топливный фильтр", "filtry-i-masla", "toplivnye-filtry", 31),
  rule("фильтр салон", "filtry-i-masla", "salonnye-filtry", 40),
  rule("салонный фильтр", "filtry-i-masla", "salonnye-filtry", 41),
  rule("фильтр", "filtry-i-masla", "maslyanye-filtry", 50),
  rule("смазк", "filtry-i-masla", "smazki", 60),
  rule("антифриз", "filtry-i-masla", "zhidkosti", 70),
  rule("тосол", "filtry-i-masla", "zhidkosti", 71),
  rule("жидкость", "filtry-i-masla", "zhidkosti", 72),
  rule("жидкость гур", "filtry-i-masla", "zhidkosti", 73),
  rule("жидкость охлажд", "filtry-i-masla", "zhidkosti", 74),

  rule("тормозн", "tormoznaya-sistema", "prochaya-tormoznaya-sistema", 10),
  rule("диск торм", "tormoznaya-sistema", "tormoznye-diski", 11),
  rule("колод", "tormoznaya-sistema", "tormoznye-kolodki", 20),
  rule("суппорт", "tormoznaya-sistema", "supporty", 30),
  rule("барабан", "tormoznaya-sistema", "barabany", 40),
  rule("цилиндр", "tormoznaya-sistema", "cilindry", 50),
  rule("шланг торм", "tormoznaya-sistema", "shlangi", 60),
  rule("тормозной шланг", "tormoznaya-sistema", "shlangi", 61),
  rule("ручник", "tormoznaya-sistema", "ruchnoy-tormoz", 62),
  rule("ручного торм", "tormoznaya-sistema", "ruchnoy-tormoz", 63),
  rule("трос руч", "tormoznaya-sistema", "ruchnoy-tormoz", 64),
  rule("вакуумн усил", "tormoznaya-sistema", "prochaya-tormoznaya-sistema", 65),
  rule("главный торм", "tormoznaya-sistema", "prochaya-tormoznaya-sistema", 66),
  rule("регулятор давления тормоз", "tormoznaya-sistema", "prochaya-tormoznaya-sistema", 67),

  rule("фара", "kuzov-i-optika", "fary", 10),
  rule("подфарник", "kuzov-i-optika", "fary", 11),
  rule("очки фар", "kuzov-i-optika", "fary", 12),
  rule("противотуманки", "kuzov-i-optika", "fary", 14),
  rule("противотуманные фары", "kuzov-i-optika", "fary", 15),
  rule("фароискатель", "kuzov-i-optika", "fary", 16),
  rule("фонар", "kuzov-i-optika", "fonari", 20),
  rule("зеркал", "kuzov-i-optika", "zerkala", 30),
  rule("стекло лоб", "kuzov-i-optika", "stekla", 31),
  rule("стекло ветров", "kuzov-i-optika", "stekla", 32),
  rule("стекло зад", "kuzov-i-optika", "stekla", 33),
  rule("стекло бок", "kuzov-i-optika", "stekla", 34),
  rule("стекло двери", "kuzov-i-optika", "stekla", 35),
  rule("решет", "kuzov-i-optika", "reshetki", 40),
  rule("бампер", "kuzov-i-optika", "bampery", 50),
  rule("молдинг", "kuzov-i-optika", "moldingi", 60),
  rule("брызговик", "kuzov-i-optika", "podkrylki-i-bryzgoviki", 61),
  rule("подкрыл", "kuzov-i-optika", "podkrylki-i-bryzgoviki", 62),
  rule("арка крыла", "kuzov-i-optika", "podkrylki-i-bryzgoviki", 63),
  rule("замок багажника", "kuzov-i-optika", "zamki-i-ruchki", 64),
  rule("замок двер", "kuzov-i-optika", "zamki-i-ruchki", 65),
  rule("ручка двер", "kuzov-i-optika", "zamki-i-ruchki", 66),
  rule("ручки двер", "kuzov-i-optika", "zamki-i-ruchki", 67),
  rule("ручка стеклопод", "kuzov-i-optika", "zamki-i-ruchki", 68),
  rule("личинк", "kuzov-i-optika", "zamki-i-ruchki", 69),
  rule("крышка бака", "kuzov-i-optika", "zamki-i-ruchki", 70),
  rule("двер", "kuzov-i-optika", "kuzovnye-detali", 70),
  rule("крыло", "kuzov-i-optika", "kuzovnye-detali", 71),
  rule("капот", "kuzov-i-optika", "kuzovnye-detali", 72),
  rule("панель", "kuzov-i-optika", "kuzovnye-detali", 73),
  rule("дефлектор", "kuzov-i-optika", "obves-i-dekor", 74),
  rule("ветровик", "kuzov-i-optika", "obves-i-dekor", 75),
  rule("спойлер", "kuzov-i-optika", "obves-i-dekor", 76),
  rule("порог", "kuzov-i-optika", "kuzovnye-detali", 77),
  rule("порожк", "kuzov-i-optika", "kuzovnye-detali", 78),

  rule("ремень", "dvigatel-i-transmissiya", "remni", 10),
  rule("грм", "dvigatel-i-transmissiya", "remni", 11),
  rule("ремня грм", "dvigatel-i-transmissiya", "remni", 12),
  rule("проклад", "dvigatel-i-transmissiya", "prokladki", 20),
  rule("насос", "dvigatel-i-transmissiya", "nasosy", 30),
  rule("помп", "dvigatel-i-transmissiya", "nasosy", 31),
  rule("сцеплен", "dvigatel-i-transmissiya", "sceplenie", 40),
  rule("пгу", "dvigatel-i-transmissiya", "sceplenie", 41),
  rule("выжимной", "dvigatel-i-transmissiya", "sceplenie", 42),
  rule("муфта выжимная", "dvigatel-i-transmissiya", "sceplenie", 43),
  rule("графитка выжим", "dvigatel-i-transmissiya", "sceplenie", 44),
  rule("кпп", "dvigatel-i-transmissiya", "kpp", 50),
  rule("коробка передач", "dvigatel-i-transmissiya", "kpp", 51),
  rule("шток выбора передач", "dvigatel-i-transmissiya", "kpp", 52),
  rule("кулиса", "dvigatel-i-transmissiya", "kpp", 53),
  rule("ремкомплект коробки", "dvigatel-i-transmissiya", "kpp", 54),
  rule("рем комплект коробки", "dvigatel-i-transmissiya", "kpp", 55),
  rule("вилка коробки", "dvigatel-i-transmissiya", "kpp", 56),
  rule("вал вторичный", "dvigatel-i-transmissiya", "kpp", 57),
  rule("первичный вал", "dvigatel-i-transmissiya", "kpp", 58),
  rule("ролик натяжного", "dvigatel-i-transmissiya", "remni", 59),
  rule("ролик поликлинов", "dvigatel-i-transmissiya", "remni", 59),
  rule("двигател", "dvigatel-i-transmissiya", "detali-dvigatelya", 60),
  rule("порш", "dvigatel-i-transmissiya", "detali-dvigatelya", 61),
  rule("сальник", "dvigatel-i-transmissiya", "detali-dvigatelya", 62),
  rule("головка блока", "dvigatel-i-transmissiya", "detali-dvigatelya", 63),
  rule("гбц", "dvigatel-i-transmissiya", "detali-dvigatelya", 64),
  rule("головки блока", "dvigatel-i-transmissiya", "detali-dvigatelya", 64),
  rule("болт головки", "dvigatel-i-transmissiya", "detali-dvigatelya", 64),
  rule("шпилька головки", "dvigatel-i-transmissiya", "detali-dvigatelya", 64),
  rule("вал коленчат", "dvigatel-i-transmissiya", "detali-dvigatelya", 64),
  rule("клапана", "dvigatel-i-transmissiya", "detali-dvigatelya", 64),
  rule("распредвал", "dvigatel-i-transmissiya", "detali-dvigatelya", 65),
  rule("коленвал", "dvigatel-i-transmissiya", "detali-dvigatelya", 66),
  rule("кол. вала", "dvigatel-i-transmissiya", "detali-dvigatelya", 67),
  rule("шкив кол", "dvigatel-i-transmissiya", "detali-dvigatelya", 68),
  rule("клапан голов", "dvigatel-i-transmissiya", "detali-dvigatelya", 69),
  rule("трансмисс", "dvigatel-i-transmissiya", "detali-transmissii", 70),
  rule("шрус", "dvigatel-i-transmissiya", "detali-transmissii", 71),
  rule("кардан", "dvigatel-i-transmissiya", "detali-transmissii", 72),
  rule("полуос", "dvigatel-i-transmissiya", "detali-transmissii", 73),
  rule("редуктор", "dvigatel-i-transmissiya", "detali-transmissii", 74),
  rule("раздатк", "dvigatel-i-transmissiya", "detali-transmissii", 75),
  rule("шарнир наружный", "dvigatel-i-transmissiya", "detali-transmissii", 76),
  rule("привод спидометра", "dvigatel-i-transmissiya", "detali-transmissii", 77),
  rule("шестерня заднего хода", "dvigatel-i-transmissiya", "detali-transmissii", 78),
  rule("блок шестер", "dvigatel-i-transmissiya", "detali-transmissii", 79),
  rule("задний мост", "dvigatel-i-transmissiya", "detali-transmissii", 79),
  rule("заднего моста", "dvigatel-i-transmissiya", "detali-transmissii", 79),
  rule("чулок заднего моста", "dvigatel-i-transmissiya", "detali-transmissii", 79),
  rule("муфта подвесная", "dvigatel-i-transmissiya", "detali-transmissii", 79),
  rule("крестовина кард", "dvigatel-i-transmissiya", "detali-transmissii", 79),
  rule("кард. вала", "dvigatel-i-transmissiya", "detali-transmissii", 79),
  rule("кард.вала", "dvigatel-i-transmissiya", "detali-transmissii", 79),
  rule("радиатор", "dvigatel-i-transmissiya", "ohlazhdenie", 80),
  rule("термостат", "dvigatel-i-transmissiya", "ohlazhdenie", 81),
  rule("расширительного бачка", "dvigatel-i-transmissiya", "ohlazhdenie", 84),
  rule("бачок расширительный", "dvigatel-i-transmissiya", "ohlazhdenie", 84),
  rule("вентилятор радиатора", "dvigatel-i-transmissiya", "ohlazhdenie", 85),
  rule("вентилятор охлажд", "dvigatel-i-transmissiya", "ohlazhdenie", 86),
  rule("карбюратор", "dvigatel-i-transmissiya", "toplivnaya-sistema", 87),
  rule("дроссель", "dvigatel-i-transmissiya", "toplivnaya-sistema", 88),
  rule("бензонасос", "dvigatel-i-transmissiya", "toplivnaya-sistema", 89),
  rule("бензобак", "dvigatel-i-transmissiya", "toplivnaya-sistema", 90),
  rule("бак топлив", "dvigatel-i-transmissiya", "toplivnaya-sistema", 91),
  rule("топливный бак", "dvigatel-i-transmissiya", "toplivnaya-sistema", 92),
  rule("глушител", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 93),
  rule("резонатор", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 94),
  rule("приемная труба", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 95),
  rule("приёмная труба", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 96),
  rule("труба приемная", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 96),
  rule("труба приёмная", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 96),
  rule("труба выхлоп", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 97),
  rule("труба выпуск", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 97),
  rule("труба промежуточ", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 97),
  rule("катализатор", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 98),
  rule("гофра глуш", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 99),
  rule("гофра трехслой", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 99),
  rule("гофра трёхслой", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 99),
  rule("хомут глуш", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 100),
  rule("система выпуска", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 101),
  rule("коллектор выпуск", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 102),
  rule("металлорукав", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 103),
  rule("металорукав", "dvigatel-i-transmissiya", "vyhlopnaya-sistema", 104),
  rule("трос газа", "dvigatel-i-transmissiya", "toplivnaya-sistema", 105),
  rule("педаль газа", "dvigatel-i-transmissiya", "toplivnaya-sistema", 106),

  rule("чехол", "aksessuary", "chehly", 10),
  rule("чехлы", "aksessuary", "chehly", 11),
  rule("коврик", "aksessuary", "kovriki", 20),
  rule("ковры", "aksessuary", "kovriki", 21),
  rule("компрессор", "aksessuary", "kompressory", 30),
  rule("рамк", "aksessuary", "ramki-nomerov", 50),
  rule("автохим", "aksessuary", "avtohimiya", 60),
  rule("органайзер", "aksessuary", "organayzery", 70),
  rule("дворник", "aksessuary", "prochie-aksessuary", 80),
  rule("антенн", "aksessuary", "prochie-aksessuary", 81),

  rule("болт м6", "krepezh", "bolty", 120),
  rule("болт м8", "krepezh", "bolty", 120),
  rule("болт м10", "krepezh", "bolty", 120),
  rule("болт м12", "krepezh", "bolty", 120),
  rule("болт 8х", "krepezh", "bolty", 120),
  rule("болт 10х", "krepezh", "bolty", 120),
  rule("din912", "krepezh", "bolty", 120),
  rule("din 912", "krepezh", "bolty", 120),
  rule("болт", "krepezh", "bolty", 121),
  rule("гайка самоконтр", "krepezh", "gayki", 122),
  rule("гайка корончатая", "krepezh", "gayki", 122),
  rule("гайка м6", "krepezh", "gayki", 122),
  rule("гайка м8", "krepezh", "gayki", 122),
  rule("гайка м10", "krepezh", "gayki", 122),
  rule("гайка м12", "krepezh", "gayki", 122),
  rule("гайк", "krepezh", "gayki", 123),
  rule("гайка", "krepezh", "gayki", 123),
  rule("шайба гровер", "krepezh", "shayby", 124),
  rule("шайба 10", "krepezh", "shayby", 124),
  rule("шайба 12", "krepezh", "shayby", 124),
  rule("гровер", "krepezh", "shayby", 124),
  rule("шайб", "krepezh", "shayby", 125),
  rule("шайба", "krepezh", "shayby", 125),
  rule("шпилька м6", "krepezh", "shpilki", 126),
  rule("шпилька м8", "krepezh", "shpilki", 126),
  rule("шпилька м10", "krepezh", "shpilki", 126),
  rule("шпильк", "krepezh", "shpilki", 127),
  rule("шпилька", "krepezh", "shpilki", 127),
  rule("винт din912", "krepezh", "vinty", 128),
  rule("внутренний шестигранник", "krepezh", "vinty", 128),
  rule("винт м3", "krepezh", "vinty", 128),
  rule("винт м4", "krepezh", "vinty", 128),
  rule("винт м5", "krepezh", "vinty", 128),
  rule("винт м6", "krepezh", "vinty", 128),
  rule("винт", "krepezh", "vinty", 129),
  rule("саморез", "krepezh", "vinty", 129),
  rule("хомут", "krepezh", "homuty", 132),
  rule("norma", "krepezh", "homuty", 132),
  rule("кольцо стопор", "krepezh", "koltsa", 134),
  rule("кольцо уплотн", "krepezh", "koltsa", 134),
  rule("кольцо резин", "krepezh", "koltsa", 134),
  rule("кольц", "krepezh", "koltsa", 135),
  rule("кольцо", "krepezh", "koltsa", 135),
  rule("штуцер переходник", "krepezh", "shtucery-i-fitingi", 136),
  rule("переходник штуцер", "krepezh", "shtucery-i-fitingi", 136),
  rule("штуцер", "krepezh", "shtucery-i-fitingi", 137),
  rule("фитинг", "krepezh", "shtucery-i-fitingi", 138),
  rule("разъем для шланг", "krepezh", "soediniteli", 139),
  rule("разъём для шланг", "krepezh", "soediniteli", 139),
  rule("быстросъем", "krepezh", "soediniteli", 139),
  rule("быстросъём", "krepezh", "soediniteli", 139),
  rule("соединител", "krepezh", "soediniteli", 139),
  rule("соединитель", "krepezh", "soediniteli", 139),
  rule("переходник", "krepezh", "soediniteli", 140),
  rule("тройник", "krepezh", "soediniteli", 141),
  rule("скоб", "krepezh", "skoby-i-kronshteyny", 142),
  rule("скоба", "krepezh", "skoby-i-kronshteyny", 142),
  rule("кронштейн", "krepezh", "skoby-i-kronshteyny", 143),

  rule("и-", "aksessuary", "instrumenty", 190),
  rule("ш-", "aksessuary", "shiny-i-diski", 191),
  rule("д-", "aksessuary", "shiny-i-diski", 192),
  rule("двг-", "dvigatel-i-transmissiya", "detali-dvigatelya", 200),
  rule("кп-", "dvigatel-i-transmissiya", "kpp", 210),
  rule("зкг-", "dvigatel-i-transmissiya", "detali-transmissii", 211),
  rule("сц-", "dvigatel-i-transmissiya", "sceplenie", 212),
  rule("сцг-", "dvigatel-i-transmissiya", "sceplenie", 213),
  rule("ре-", "podveska", "ressory", 214),
  rule("эо-", "elektrika", "prochaya-elektrika", 220),
  rule("эог-", "elektrika", "prochaya-elektrika", 221),
  rule("гсм-", "filtry-i-masla", "zhidkosti", 230),
  rule("тс-", "tormoznaya-sistema", "prochaya-tormoznaya-sistema", 240),
  rule("тсг-", "tormoznaya-sistema", "prochaya-tormoznaya-sistema", 241),
  rule("ж-", "kuzov-i-optika", "kuzovnye-detali", 250),
  rule("жл-", "kuzov-i-optika", "kuzovnye-detali", 251),
  rule("кз-", "kuzov-i-optika", "kuzovnye-detali", 252)
] as const;

export const deprecatedCategorizationRules = [
  deprecatedRule("воздушн"),
  deprecatedRule("топлив"),
  deprecatedRule("салон"),
  deprecatedRule("шланг"),
  deprecatedRule("патрубок радиатор", "dvigatel-i-transmissiya", "ohlazhdenie"),
  deprecatedRule("патрубки печки", "dvigatel-i-transmissiya", "ohlazhdenie"),
  deprecatedRule("стекло фары", "kuzov-i-optika", "fary"),
  deprecatedRule("стекло фар", "kuzov-i-optika", "fary")
] as const;

function rule(pattern: string, categorySlug: string, subcategorySlug: string, priority: number) {
  return {
    pattern,
    matchType: "contains",
    categorySlug,
    subcategorySlug,
    priority
  } as const;
}

function deprecatedRule(pattern: string, categorySlug?: string, subcategorySlug?: string) {
  return {
    pattern,
    matchType: "contains",
    categorySlug,
    subcategorySlug
  } as const;
}
