export const DOMAIN_DICTIONARY_VERSION = "domain-dictionary-v2";
export const DOMAIN_RULES_VERSION = "domain-rules-v2";
export const CONFIDENCE_MODEL_VERSION = "confidence-model-v2";
export const GROUPING_MODEL_VERSION = "grouping-v2";

export interface ProductFamilyDefinition {
  id: string;
  label: string;
  categorySlug: string;
  subcategorySlug: string;
  requiredAny: string[];
  requiredAll?: string[];
  contextAny?: string[];
  strongPhrases?: string[];
  optional?: string[];
  technicalAny?: string[];
  negative?: string[];
  groupable: boolean;
  autoReadyMinEvidence: number;
  baseConfidence: number;
  description: string;
}

export const weakGeneralTokens = new Set([
  "авто",
  "автомобильный",
  "блок",
  "деталь",
  "комплект",
  "корпус",
  "модуль",
  "набор",
  "универсальный",
  "элемент"
]);

export const dangerousBroadTokens = new Set([
  "болт",
  "гайка",
  "винт",
  "втулка",
  "датчик",
  "диск",
  "жидкость",
  "клапан",
  "кольцо",
  "крепление",
  "кронштейн",
  "лента",
  "мост",
  "насос",
  "накладка",
  "патрубок",
  "провод",
  "ремкомплект",
  "ремень",
  "ручка",
  "сальник",
  "сигнал",
  "стекло",
  "трос",
  "трубка",
  "фитинг",
  "фильтр",
  "хомут",
  "щетка",
  "щётка",
  "шайба",
  "шланг",
  "шпилька",
  "штуцер"
]);

const otherProductsNegativeContext = [
  "амортизатор",
  "антенн",
  "бампер",
  "бак",
  "гбц",
  "генератор",
  "глушител",
  "двер",
  "двигател",
  "диск",
  "зажиган",
  "кардан",
  "картер",
  "коленвал",
  "колес",
  "колесн",
  "компрессор",
  "кпп",
  "кресл",
  "кузов",
  "мост",
  "омывател",
  "охлажд",
  "патрубок",
  "подвеск",
  "прикурив",
  "радиатор",
  "рессор",
  "ручк",
  "салаз",
  "рулев",
  "салон",
  "свеч",
  "сцеплен",
  "сидень",
  "суп",
  "стекл",
  "ступиц",
  "суппорт",
  "тормоз",
  "топлив",
  "трубк",
  "фар",
  "фонар",
  "форсунк",
  "шрус"
];

export const familyDefinitions: ProductFamilyDefinition[] = [
  family({
    id: "automotive_bulb",
    label: "Лампы",
    categorySlug: "elektrika",
    subcategorySlug: "lampy",
    requiredAny: ["лампа", "лампочка"],
    strongPhrases: ["лампа t10", "лампа w5w", "лампа h7", "лампа h4", "лампа h1"],
    technicalAny: ["t10", "w5w", "h1", "h4", "h7", "12v", "24v", "led"],
    negative: ["фара", "фонарь", "настольная", "переноска"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.91,
    description: "Автомобильная лампа с цоколем, напряжением или LED-признаком."
  }),
  family({
    id: "oil_filter",
    label: "Масляные фильтры",
    categorySlug: "filtry-i-masla",
    subcategorySlug: "maslyanye-filtry",
    requiredAny: ["фильтр"],
    requiredAll: ["масляный"],
    strongPhrases: ["фильтр масляный", "масляный фильтр", "фильтр масл"],
    negative: ["воздушный", "салонный", "топливный", "акпп"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.93,
    description: "Фильтр с явным масляным контекстом."
  }),
  family({
    id: "air_filter",
    label: "Воздушные фильтры",
    categorySlug: "filtry-i-masla",
    subcategorySlug: "vozdushnye-filtry",
    requiredAny: ["фильтр"],
    requiredAll: ["воздушный"],
    strongPhrases: ["фильтр воздушный", "воздушный фильтр"],
    negative: ["масляный", "салонный", "топливный"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.93,
    description: "Фильтр с явным воздушным контекстом."
  }),
  family({
    id: "cabin_filter",
    label: "Салонные фильтры",
    categorySlug: "filtry-i-masla",
    subcategorySlug: "salonnye-filtry",
    requiredAny: ["фильтр"],
    requiredAll: ["салонный"],
    strongPhrases: ["фильтр салонный", "салонный фильтр", "фильтр салона"],
    negative: ["масляный", "воздушный", "топливный"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.93,
    description: "Фильтр с явным салонным контекстом."
  }),
  family({
    id: "fuel_filter",
    label: "Топливные фильтры",
    categorySlug: "filtry-i-masla",
    subcategorySlug: "toplivnye-filtry",
    requiredAny: ["фильтр"],
    requiredAll: ["топливный"],
    strongPhrases: ["фильтр топливный", "топливный фильтр"],
    negative: ["масляный", "воздушный", "салонный"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.92,
    description: "Фильтр с явным топливным контекстом."
  }),
  family({
    id: "brake_pads",
    label: "Тормозные колодки",
    categorySlug: "tormoznaya-sistema",
    subcategorySlug: "tormoznye-kolodki",
    requiredAny: ["колодка", "колодки"],
    requiredAll: ["тормозной"],
    strongPhrases: ["колодки тормозные", "тормозные колодки", "торм колодки"],
    negative: ["накладка", "диск"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.94,
    description: "Колодки с тормозным контекстом."
  }),
  family({
    id: "brake_disc",
    label: "Тормозные диски",
    categorySlug: "tormoznaya-sistema",
    subcategorySlug: "tormoznye-diski",
    requiredAny: ["диск"],
    requiredAll: ["тормозной"],
    strongPhrases: ["диск тормозной", "тормозной диск"],
    negative: ["колесный", "сцепления", "абразивный"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.94,
    description: "Диск с тормозным контекстом; одиночное слово диск не используется."
  }),
  family({
    id: "brake_fluid",
    label: "Тормозная жидкость",
    categorySlug: "filtry-i-masla",
    subcategorySlug: "zhidkosti",
    requiredAny: ["жидкость"],
    requiredAll: ["тормозной"],
    strongPhrases: ["тормозная жидкость", "жидкость тормозная", "dot 4", "dot4"],
    technicalAny: ["dot4", "dot3", "dot5"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.94,
    description: "Техническая жидкость с DOT или тормозным контекстом."
  }),
  family({
    id: "motor_oil",
    label: "Моторные масла",
    categorySlug: "filtry-i-masla",
    subcategorySlug: "masla",
    requiredAny: ["масло"],
    strongPhrases: ["масло моторное", "моторное масло", "масло двигательное"],
    technicalAny: ["5w30", "5w-30", "10w40", "10w-40", "atf"],
    negative: ["фильтр"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.91,
    description: "Масло с вязкостью, моторным или трансмиссионным контекстом."
  }),
  family({
    id: "antifreeze",
    label: "Антифризы и тосол",
    categorySlug: "filtry-i-masla",
    subcategorySlug: "zhidkosti",
    requiredAny: ["антифриз", "тосол", "охлаждающая"],
    strongPhrases: ["охлаждающая жидкость"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.93,
    description: "Охлаждающая жидкость, антифриз или тосол."
  }),
  family({
    id: "gasket",
    label: "Прокладки",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "prokladki",
    requiredAny: ["прокладка", "паронит"],
    strongPhrases: ["прокладка гбц", "прокладка клапанной крышки", "паронит прокладочный"],
    negative: ["герметик"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.9,
    description: "Прокладки и прокладочный паронит."
  }),
  family({
    id: "spark_plug",
    label: "Свечи зажигания",
    categorySlug: "elektrika",
    subcategorySlug: "svechi-zazhiganiya",
    requiredAny: ["свеча", "свечи"],
    strongPhrases: ["свеча зажигания", "свечи зажигания"],
    negative: ["ключ", "головка"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.93,
    description: "Свечи зажигания без инструментального контекста."
  }),
  family({
    id: "ignition_coil",
    label: "Катушки зажигания",
    categorySlug: "elektrika",
    subcategorySlug: "prochaya-elektrika",
    requiredAny: ["катушка"],
    requiredAll: ["зажигания"],
    strongPhrases: ["катушка зажигания"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.91,
    description: "Катушка с явным контекстом зажигания."
  }),
  family({
    id: "battery",
    label: "Аккумуляторы",
    categorySlug: "elektrika",
    subcategorySlug: "akkumulyatory",
    requiredAny: ["акб", "аккумулятор"],
    negative: ["зарядное", "клемма"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.94,
    description: "Аккумулятор или АКБ; зарядные устройства не включаются."
  }),
  family({
    id: "starter",
    label: "Стартеры",
    categorySlug: "elektrika",
    subcategorySlug: "startery",
    requiredAny: ["стартер"],
    negative: ["ремкомплект", "бендикс", "втягивающее"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.91,
    description: "Стартер без явного признака ремкомплекта."
  }),
  family({
    id: "generator",
    label: "Генераторы",
    categorySlug: "elektrika",
    subcategorySlug: "generatory",
    requiredAny: ["генератор"],
    negative: ["ремень", "щетка", "реле"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.91,
    description: "Генератор без контекста ремня или мелких комплектующих."
  }),
  family({
    id: "electrical_misc",
    label: "Прочая электрика",
    categorySlug: "elektrika",
    subcategorySlug: "prochaya-elektrika",
    requiredAny: [
      "переключатель",
      "кнопка",
      "стеклоподъемник",
      "стеклоподъёмник",
      "электростеклоподъемник",
      "электростеклоподъёмник",
      "компьютер",
      "корректор"
    ],
    strongPhrases: ["октан корректор", "переключатель салонный", "электростеклоподъемник двери"],
    negative: ["бортовой компьютер ноутбук", "usb"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.85,
    description: "Электрические переключатели, стеклоподъёмники и автомобильные электронные блоки."
  }),
  family({
    id: "sensor",
    label: "Датчики",
    categorySlug: "elektrika",
    subcategorySlug: "datchiki",
    requiredAny: ["датчик", "дмрв", "дпкв", "дпдз", "рхх"],
    negative: ["под датчик", "без датчика"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.87,
    description: "Датчики и устойчивые сокращения датчиков; одиночный общий сигнал уходит в групповое подтверждение."
  }),
  family({
    id: "wiring",
    label: "Проводка",
    categorySlug: "elektrika",
    subcategorySlug: "provodka",
    requiredAny: ["провод", "проводка", "жгут", "разъем", "разьем", "фишка", "клемма"],
    strongPhrases: ["провод высоковольтный", "жгут проводов", "клемма аккумулятора"],
    negative: ["usb", "aux", "зарядное"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.87,
    description: "Проводка, разъёмы и клеммы с автомобильным контекстом."
  }),
  family({
    id: "electrical_tape",
    label: "Изолента и электромонтажные ленты",
    categorySlug: "elektrika",
    subcategorySlug: "provodka",
    requiredAny: ["изолента", "термоусадка", "термоусад"],
    strongPhrases: ["изолента", "термоусадочная трубка"],
    negative: ["малярный", "упаковочный", "двухсторонний"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.83,
    description: "Электромонтажные ленты группируются как проводка только при явном электрическом назначении."
  }),
  family({
    id: "led_strips",
    label: "Диодные ленты и доп. освещение",
    categorySlug: "elektrika",
    subcategorySlug: "osveshchenie",
    requiredAny: ["лента", "подсветка"],
    contextAny: ["диод", "led", "12v", "24v"],
    strongPhrases: ["лента диодная", "диодная лента", "led лента"],
    negative: ["стропа", "скотч", "малярный"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Светодиодные ленты и подсветка с явным LED/12V контекстом."
  }),
  family({
    id: "usb_power_accessories",
    label: "USB-питание и автомобильные переходники",
    categorySlug: "elektrika",
    subcategorySlug: "prochaya-elektrika",
    requiredAny: ["usb", "зарядное", "переходник", "разветвитель"],
    contextAny: ["прикурив", "12v", "24v", "вольтметр", "автомоб", "заряд"],
    strongPhrases: ["переходник прикуривателя", "разветвитель прикуривателя", "зарядное устройство usb"],
    negative: ["samsung", "iphone", "флешка", "карта памяти"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Автомобильные USB-переходники отделяются от бытовых USB-аксессуаров."
  }),
  family({
    id: "small_electrical_gauges",
    label: "Автомобильные измерители и приборы",
    categorySlug: "elektrika",
    subcategorySlug: "prochaya-elektrika",
    requiredAny: ["вольтметр", "тахометр", "термометр"],
    contextAny: ["12v", "24v", "врезной", "автомоб", "часы", "внутр"],
    strongPhrases: ["вольтметр врезной", "тахометр", "термометр внутренний"],
    negative: ["инфракрасный", "бытовой"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Автомобильные вольтметры, тахометры и салонные термометры."
  }),
  family({
    id: "central_locking",
    label: "Центральный замок",
    categorySlug: "elektrika",
    subcategorySlug: "prochaya-elektrika",
    requiredAny: ["замок", "привод"],
    contextAny: ["центральный"],
    strongPhrases: ["центральный замок", "привод центрального замка"],
    negative: ["руль", "педал"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Электроприводы и комплекты центрального замка."
  }),
  family({
    id: "anti_theft_locks",
    label: "Противоугонные замки",
    categorySlug: "aksessuary",
    subcategorySlug: "bezopasnost",
    requiredAny: ["замок"],
    contextAny: ["руль", "педал"],
    strongPhrases: ["замок на руль", "замок на педали"],
    negative: ["двер", "багажник", "центральный"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Противоугонные замки на руль или педали."
  }),
  family({
    id: "seat_belts",
    label: "Ремни безопасности",
    categorySlug: "aksessuary",
    subcategorySlug: "bezopasnost",
    requiredAny: ["ремень", "ремни", "ремня"],
    contextAny: ["безопас"],
    strongPhrases: ["ремни безопасности", "ремень безопасности", "ремня безопасности"],
    negative: ["грм", "генератор", "приводной", "крепления"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.86,
    description: "Ремни безопасности выделяются отдельно от приводных ремней и подтверждаются группой."
  }),
  family({
    id: "portable_work_lights",
    label: "Переносные автомобильные светильники",
    categorySlug: "elektrika",
    subcategorySlug: "osveshchenie",
    requiredAny: ["переноска", "прожектор"],
    contextAny: ["12v", "24v", "галоген", "диод", "магнит", "дневной"],
    strongPhrases: ["переноска 12v", "переноска 24v", "переноска галогеновая", "переноска диодная"],
    negative: ["220v", "бытовой"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.84,
    description: "Переноски и прожекторы группируются как освещение только при автомобильном напряжении или световом контексте."
  }),
  family({
    id: "car_clocks",
    label: "Автомобильные часы",
    categorySlug: "elektrika",
    subcategorySlug: "prochaya-elektrika",
    requiredAny: ["часы"],
    contextAny: ["подсвет", "стекло", "салон", "2106", "авто"],
    strongPhrases: ["часы с подсветкой", "часы на стекло"],
    negative: ["наручные", "настенные"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.82,
    description: "Автомобильные часы и салонные часы попадают только в групповое подтверждение."
  }),
  family({
    id: "belt",
    label: "Ремни",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "remni",
    requiredAny: ["ремень", "ремни"],
    negative: ["безопасности", "крепления"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.9,
    description: "Ремни двигателя/привода; ремни безопасности исключаются."
  }),
  family({
    id: "timing_kit",
    label: "ГРМ и ролики",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "remni",
    requiredAny: ["грм", "ролик"],
    strongPhrases: ["ремень грм", "комплект грм", "ролик натяжной", "ролик натяжителя"],
    negative: ["двери", "стекло"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.91,
    description: "Ремни и ролики ГРМ/натяжителя."
  }),
  family({
    id: "pump_engine",
    label: "Насосы двигателя",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "nasosy",
    requiredAny: ["насос", "помпа"],
    strongPhrases: ["насос водяной", "насос топливный", "насос масляный", "помпа водяная"],
    negative: ["ножной", "ручной", "электрический", "электр", "шин", "омывател"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.86,
    description: "Насосы узлов двигателя; одиночное слово насос подтверждается группой."
  }),
  family({
    id: "engine_parts",
    label: "Детали двигателя",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["поршень", "поршневой", "коленвал", "распредвал", "гильза", "коромысло", "шестерня"],
    strongPhrases: ["кольцо поршневое", "кольца поршневые", "вал коленчатый", "вал распределительный"],
    negative: ["карданный", "приводной", "рулевой"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.86,
    description: "Узкие детали двигателя с проверяемыми контекстными словами."
  }),
  family({
    id: "cooling",
    label: "Охлаждение",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "ohlazhdenie",
    requiredAny: ["радиатор", "термостат", "диффузор"],
    strongPhrases: ["вентилятор охлаждения", "радиатор охлаждения", "радиатор печки", "радиатор отопителя"],
    negative: ["салона", "лобовой", "настольный", "тепловентилятор"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.86,
    description: "Радиаторы, вентиляторы и элементы системы охлаждения."
  }),
  family({
    id: "cooling_fans",
    label: "Электровентиляторы охлаждения",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "ohlazhdenie",
    requiredAny: ["электровентилятор", "вентилятор"],
    contextAny: ["охлажд", "радиатор", "двигател", "калина", "приора", "нива"],
    strongPhrases: ["электровентилятор", "вентилятор охлаждения", "вентилятор радиатора"],
    negative: ["салон", "тепловентилятор", "comfort", "обогрев"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Вентиляторы двигателя/радиатора без салонных и бытовых вентиляторов."
  }),
  family({
    id: "heater_electrical_parts",
    label: "Электрика печки",
    categorySlug: "elektrika",
    subcategorySlug: "prochaya-elektrika",
    requiredAny: ["мотор", "сопротивление", "переключатель", "блок"],
    contextAny: ["печк", "отопител"],
    strongPhrases: ["мотор печки", "сопротивление печки", "переключатель печки", "блок переключения печки"],
    negative: ["кран", "патрубок", "трубка"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.85,
    description: "Электрические элементы печки отделяются от кранов, патрубков и корпуса отопителя."
  }),
  family({
    id: "heater_cooling_parts",
    label: "Печка и отопитель",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "ohlazhdenie",
    requiredAny: ["печка", "печки", "отопитель", "кран", "корпус", "кожух", "отвод", "трубка", "трубки"],
    contextAny: ["печк", "отопител"],
    strongPhrases: ["кран печки", "корпус печки", "кожух печки", "отвод печки", "трубки печки", "печка в сборе"],
    negative: ["переключатель", "сопротивление", "мотор"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.84,
    description: "Краны, корпус и трубки печки группируются как охлаждение/отопитель, но не публикуются автоматически."
  }),
  family({
    id: "cooling_hoses",
    label: "Патрубки и шланги охлаждения",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "patrubki-i-shlangi-ohlazhdeniya",
    requiredAny: ["патрубок", "патрубки", "шланг", "шланги", "тройник", "соединитель"],
    requiredAll: ["радиатор"],
    strongPhrases: ["патрубок радиатора", "шланг радиатора", "тройник радиатора"],
    negative: ["тормозной", "топливный", "гур"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.85,
    description: "Шланги, патрубки и соединители системы охлаждения."
  }),
  family({
    id: "fuel_system",
    label: "Топливная система",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "toplivnaya-sistema",
    requiredAny: [
      "бензобак",
      "бензин",
      "бензиновый",
      "карбюратор",
      "форсунка",
      "форсунки",
      "форсунок",
      "топливный",
      "топливная",
      "топливн"
    ],
    strongPhrases: [
      "бачок топливный",
      "бак топливный",
      "шланг бензиновый",
      "шланг топливный",
      "трубка бензиновая",
      "трубка топливная",
      "трубки топливные",
      "планка форсунок",
      "рампа форсунок"
    ],
    negative: ["фильтр", "омывател"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.87,
    description: "Топливные баки, карбюраторы, форсунки и топливные магистрали."
  }),
  family({
    id: "throttle_cables",
    label: "Тросы газа",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "toplivnaya-sistema",
    requiredAny: ["трос", "скоба", "кронштейн", "тяга"],
    contextAny: ["газа", "газовой", "подсос", "дроссел", "акселератор"],
    strongPhrases: ["трос газа", "скоба троса газа", "кронштейн троса газа", "тяга газа", "тяга акселератора"],
    negative: ["тормоз", "ручник", "сцеплен", "спидометр", "капот", "газель"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Тросы и крепления газа/подсоса с явным топливным контекстом."
  }),
  family({
    id: "kpp_parts",
    label: "КПП",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "kpp",
    requiredAny: ["кулиса", "кулис", "муфта", "коробка"],
    strongPhrases: ["кулиса кпп", "муфта кпп", "коробки передач", "вилка кпп", "ремкомплект кулисы"],
    negative: ["сцепления", "рулевая", "кардан"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.85,
    description: "Кулисы, муфты и детали коробки передач."
  }),
  family({
    id: "gearbox_cables",
    label: "Тросы КПП",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "kpp",
    requiredAny: ["трос"],
    contextAny: ["кпп", "передач", "переключ"],
    strongPhrases: ["трос кпп", "трос переключения передач", "трос перекл передач"],
    negative: ["ручной тормоз", "стояноч", "газ", "спидометр", "капот"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Тросы выбора/переключения передач."
  }),
  family({
    id: "engine_valves",
    label: "Детали двигателя",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["клапан", "клапаны", "клапанов", "тарелка", "втулка", "втулки"],
    contextAny: ["клапан", "клапанн", "клапанов", "гбц", "голов", "двигател", "впуск", "выпуск", "кл", "16v", "8v"],
    strongPhrases: [
      "втулки клапанов",
      "втулка клапанов",
      "тарелки клапанов",
      "клапан двигателя",
      "клапан гбц",
      "клапаны 16",
      "клапаны 8"
    ],
    negative: ["рециркуляции", "электромагнитный", "обратки", "паров", "сепаратора"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.84,
    description: "Клапаны и связанные детали двигателя."
  }),
  family({
    id: "exhaust",
    label: "Выхлопная система",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "vyhlopnaya-sistema",
    requiredAny: ["глушитель", "резонатор", "нейтрализатор", "гофра", "пламегаситель"],
    strongPhrases: ["приемная труба", "труба приемная", "насадка глушителя"],
    negative: ["пыльник"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.89,
    description: "Глушители, резонаторы, гофры и приемные трубы."
  }),
  family({
    id: "shock_absorber",
    label: "Амортизаторы",
    categorySlug: "podveska",
    subcategorySlug: "amortizatory",
    requiredAny: ["амортизатор", "амортиз"],
    negative: ["багажника", "капота"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.91,
    description: "Амортизаторы подвески; газовые упоры капота/багажника исключаются."
  }),
  family({
    id: "spring",
    label: "Пружины",
    categorySlug: "podveska",
    subcategorySlug: "pruzhiny",
    requiredAny: ["пружина", "пружины"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.9,
    description: "Пружины подвески и близких узлов."
  }),
  family({
    id: "hub_bearing",
    label: "Ступицы и ступичные подшипники",
    categorySlug: "podveska",
    subcategorySlug: "stupicy",
    requiredAny: ["ступица", "ступичный"],
    strongPhrases: ["подшипник ступицы", "ступичный подшипник"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.92,
    description: "Ступицы и подшипники ступицы."
  }),
  family({
    id: "bearing",
    label: "Подшипники",
    categorySlug: "podveska",
    subcategorySlug: "podshipniki",
    requiredAny: ["подшипник"],
    negative: ["ступица", "ступичный"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.88,
    description: "Подшипники без ступичного контекста идут в быстрые группы."
  }),
  family({
    id: "silentblock",
    label: "Сайлентблоки",
    categorySlug: "podveska",
    subcategorySlug: "saylentbloki",
    requiredAny: ["сайлентблок", "сайлент"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.92,
    description: "Сайлентблоки."
  }),
  family({
    id: "ball_joint",
    label: "Шаровые опоры",
    categorySlug: "podveska",
    subcategorySlug: "sharovye-opory",
    requiredAny: ["шаровая", "шаров"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.91,
    description: "Шаровые опоры."
  }),
  family({
    id: "tie_rod",
    label: "Рулевые тяги",
    categorySlug: "podveska",
    subcategorySlug: "rulevye-tyagi",
    requiredAny: ["тяга"],
    requiredAll: ["рулевой"],
    strongPhrases: ["рулевая тяга", "тяга рул"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.93,
    description: "Рулевые тяги."
  }),
  family({
    id: "steering_tip",
    label: "Рулевые наконечники",
    categorySlug: "podveska",
    subcategorySlug: "rulevye-nakonechniki",
    requiredAny: ["наконечник"],
    requiredAll: ["рулевой"],
    strongPhrases: ["рулевой наконечник", "наконечник рул"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.93,
    description: "Рулевые наконечники."
  }),
  family({
    id: "suspension_arm",
    label: "Рычаги",
    categorySlug: "podveska",
    subcategorySlug: "rychagi",
    requiredAny: ["рычаг", "растяжка"],
    negative: ["переключения", "стеклоочистителя"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.87,
    description: "Рычаги и растяжки подвески."
  }),
  family({
    id: "suspension_hardware",
    label: "Метизы и малые детали подвески",
    categorySlug: "podveska",
    subcategorySlug: "prochaya-podveska",
    requiredAny: ["болт", "болты", "гайка", "шайба", "скоба", "палец", "кронштейн", "ремкомплект"],
    contextAny: ["развал", "растяжк", "реактивн", "штанг", "балк", "подвеск", "стойк", "амортизатор"],
    strongPhrases: [
      "болт развала",
      "шайба развала",
      "шайба растяжки",
      "реактивная штанга",
      "реактивных болтов",
      "кронштейн задней балки",
      "ремкомплект стоек"
    ],
    negative: ["двигател", "кпп", "кардан", "колес", "глушител", "суппорт", "генератор"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.84,
    description: "Подвесочный крепёж группируется только при явном контексте развала, растяжек, балки или стоек."
  }),
  family({
    id: "tow_ropes",
    label: "Буксировочные тросы и стропы",
    categorySlug: "aksessuary",
    subcategorySlug: "bezopasnost",
    requiredAny: ["трос", "стропа", "карабин", "скоба", "палец", "крюк"],
    contextAny: ["буксир", "такелаж", "динамическ", "крюк", "крюками", "проушин", "петл", "ленточн", "двухпетлевая"],
    strongPhrases: ["трос буксировочный", "динамический трос", "скоба такелажная", "крюк буксировочный", "стропа двухпетлевая"],
    negative: ["тормоз", "ручник", "газ", "сцеплен", "спидометр", "капот", "кпп"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.86,
    description: "Буксировочные тросы, стропы, такелажные скобы и крюки без смешения с функциональными тросами автомобиля."
  }),
  family({
    id: "cleaning_brushes",
    label: "Щетки и скребки для ухода",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["щетка", "щетки", "щётка", "щётки", "скребок", "водосгон"],
    contextAny: ["снег", "мыть", "мойки", "телескоп", "скреб", "ручк", "уход"],
    strongPhrases: ["щетка для снега", "щётка для снега", "щетка для мытья", "водосгон", "набор для мойки"],
    negative: ["стеклоочист", "с/очист", "дворник"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Инструменты ухода за стеклом/кузовом отделены от щеток стеклоочистителя."
  }),
  family({
    id: "care_consumables",
    label: "Салфетки и расходники ухода",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["салфетка", "салфетки", "микрофибра", "полотенца"],
    contextAny: ["уход", "мойки", "комплексного", "авто", "универсальные"],
    strongPhrases: ["набор салфеток", "микрофибра", "полотенца универсальные"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Салфетки, микрофибра и расходники ухода за автомобилем."
  }),
  family({
    id: "washing_sponges",
    label: "Губки и расходники мойки",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["губка", "швабра"],
    contextAny: ["мыть", "мойки", "пластик", "поролон", "крупнопорист", "авто"],
    strongPhrases: ["губка для мытья", "губка для пластика", "швабра для мытья"],
    negative: ["топлив", "фильтр", "бензонасос"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.82,
    description: "Губки и швабры ухода группируются на подтверждение без автопринятия."
  }),
  family({
    id: "car_fragrances",
    label: "Ароматизаторы и дезодоранты",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["ароматизатор", "ароматизаторы", "дезодорант"],
    strongPhrases: ["ароматизатор", "дезодорант"],
    negative: ["бытовой", "обуви", "помещений"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.82,
    description: "Ароматизаторы и дезодоранты оставляются группой на подтверждение, так как локальных активных аналогов нет."
  }),
  family({
    id: "adhesive_tapes",
    label: "Скотч и клейкие ленты",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["скотч"],
    contextAny: ["армирован", "малярн", "прозрачн", "сторон", "боди", "car", "мм"],
    strongPhrases: ["скотч армированный", "скотч малярный", "скотч двухсторонний"],
    negative: ["антискотч", "удалитель"],
    autoReadyMinEvidence: 4,
    baseConfidence: 0.82,
    description: "Клейкие ленты как узкая низкоуверенная accessory-группа для подтверждения."
  }),
  family({
    id: "steering_wheel_accessories",
    label: "Аксессуары руля",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["оплетка", "оплётка", "ручка", "накладка"],
    contextAny: ["руля", "руль"],
    strongPhrases: ["оплетка руля", "оплётка руля", "ручка руля"],
    negative: ["рулевая тяга", "рулевой наконечник", "кардан рул"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Оплетки и ручки руля без смешения с рулевыми деталями подвески."
  }),
  family({
    id: "steering_wheel_covers",
    label: "Оплетки руля",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["оплетка", "оплётка"],
    strongPhrases: ["оплетка", "оплётка", "оплетка руля", "оплётка руля"],
    negative: ["провод", "шланг"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.84,
    description: "Оплетки руля имеют однородные активные аналоги, но новые позиции подтверждаются группой."
  }),
  family({
    id: "steering_wheels",
    label: "Рули и рулевые колеса",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["руль"],
    strongPhrases: ["руль самара", "руль москвич", "руль 2110"],
    negative: ["шина", "колес", "колёс", "диск", "оплетка", "оплётка", "накладка", "замок", "тяга", "наконечник"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.82,
    description: "Рули группируются по существующим активным аналогам кузовных деталей, но не подтверждаются автоматически."
  }),
  family({
    id: "child_seats",
    label: "Детские автокресла",
    categorySlug: "aksessuary",
    subcategorySlug: "bezopasnost",
    requiredAny: ["автокресло", "кресло", "сидение"],
    contextAny: ["детск", "ребен", "ребён", "люлька", "15-36", "9-36", "смешарики"],
    strongPhrases: ["детское кресло", "детское автокресло", "сидение детское"],
    negative: ["кронштейн", "фиксатор", "вал"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.82,
    description: "Детские кресла относятся к безопасности, но без активной опоры идут только в групповую проверку."
  }),
  family({
    id: "floor_mats",
    label: "Коврики и ковры",
    categorySlug: "aksessuary",
    subcategorySlug: "kovriki",
    requiredAny: ["коврик", "коврики", "ковер", "ковёр", "ковры"],
    contextAny: ["пола", "салон", "багажник", "eva", "резин"],
    strongPhrases: ["ковер пола", "ковёр пола", "коврик багажника", "коврики салона"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Коврики, ковры пола и багажника."
  }),
  family({
    id: "seat_covers",
    label: "Чехлы и накидки сидений",
    categorySlug: "aksessuary",
    subcategorySlug: "chehly",
    requiredAny: ["чехол", "чехлы", "накидка", "накидки", "маечки"],
    contextAny: ["сидень", "сиден", "сидения", "салон", "кресл", "массаж", "мехов", "передн"],
    strongPhrases: ["накидка на сидение", "накидки сидений", "накидка сидений", "чехлы сидений", "маечки-чехлы"],
    negative: ["двигател", "коробк", "руль"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Чехлы и накидки сидений без смешения с деталями агрегатов."
  }),
  family({
    id: "seat_structural_parts",
    label: "Крепления и детали сидений",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["кронштейн", "фиксатор", "гребенка", "гребёнка", "вал", "перемычка", "скоба"],
    contextAny: ["сидень", "сиден", "сидения"],
    strongPhrases: ["кронштейн сиденья", "фиксатор сиденья", "гребенка сиденья", "перемычка сидений"],
    negative: ["чехол", "накидка", "подогрев", "обогрев"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.82,
    description: "Конструктивные детали сидений подтверждаются группой по активным кузовным аналогам."
  }),
  family({
    id: "wheel_caps",
    label: "Колпаки колес",
    categorySlug: "aksessuary",
    subcategorySlug: "shiny-i-diski",
    requiredAny: ["колпаки", "колпак"],
    contextAny: ["хром", "д.", "r13", "r14", "r15", "r16", "13", "14", "15", "16", "17", "газель", "волга"],
    strongPhrases: ["колпаки", "колпаки хром", "колпаки декоративные", "колпаки газель", "колпаки волга"],
    negative: ["защитный", "кронштейн", "крепления", "ступицы"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Декоративные колёсные колпаки; защитные колпаки узлов не включаются."
  }),
  family({
    id: "car_audio",
    label: "Автоаудио",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["магнитола", "автомагнитола", "колонки", "автоколонки", "динамик", "динамиков", "сабвуфер", "савбуфер", "антенна"],
    strongPhrases: ["автомагнитола", "автоколонки", "колонки автомобильные", "кольца проставочные динамиков", "сабвуфер"],
    negative: ["ремкомплект", "провод"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Автомобильные аудиоустройства и связанные аксессуары."
  }),
  family({
    id: "car_vacuums",
    label: "Автопылесосы",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["пылесос"],
    strongPhrases: ["пылесос"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.84,
    description: "Автомобильные пылесосы как узкая accessory-группа."
  }),
  family({
    id: "driver_electronics",
    label: "Водительская электроника",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["антирадар", "алкотестер", "рация", "телевизор", "инвертор", "мультитроник"],
    contextAny: ["автомобильный", "12", "220", "оптим", "cobra", "sho-me", "alan", "megajet"],
    strongPhrases: ["антирадар", "алкотестер", "автомобильный телевизор", "автомобильный инвертор", "мультитроник"],
    negative: ["датчик", "генератор", "стартер"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.83,
    description: "Антирадары, алкотестеры, рации и автоинверторы остаются группой для подтверждения."
  }),
  family({
    id: "roof_rails",
    label: "Рейлинги и багажные аксессуары",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["рейлинг", "рейлинги"],
    strongPhrases: ["багажник на рейлинги", "рейлинги"],
    negative: ["съемник", "съёмник"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.83,
    description: "Рейлинги и багажники на рейлинги группируются по активным accessory-аналогам."
  }),
  family({
    id: "printed_accessories",
    label: "Печатные материалы",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["книг", "каталог", "блокнот", "атлас"],
    strongPhrases: ["книги за рулем", "книги волга", "книги иномарки", "атлас дорог"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.84,
    description: "Книги, каталоги и блокноты из accessory-раздела."
  }),
  family({
    id: "document_accessories",
    label: "Автодокументы и футляры",
    categorySlug: "aksessuary",
    subcategorySlug: "organayzery",
    requiredAny: ["автодокументы", "футляр"],
    contextAny: ["паспорт", "кошелек", "кошелёк", "очков", "документ"],
    strongPhrases: ["автодокументы", "футляр для очков"],
    negative: ["инструмент", "ремкомплект"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.82,
    description: "Футляры и документы водителя идут в органайзеры только через групповое подтверждение."
  }),
  family({
    id: "safety_stands",
    label: "Страховочные подставки",
    categorySlug: "aksessuary",
    subcategorySlug: "bezopasnost",
    requiredAny: ["подставка"],
    contextAny: ["страхов", "машину", "авто"],
    strongPhrases: ["подставка страховочная", "подставка под машину", "подставка под авто"],
    negative: ["ока длинная"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Страховочные подставки под автомобиль."
  }),
  family({
    id: "seat_heaters",
    label: "Подогревы сидений",
    categorySlug: "elektrika",
    subcategorySlug: "prochaya-elektrika",
    requiredAny: ["подогрев", "обогрев"],
    contextAny: ["сидень", "сидушка"],
    strongPhrases: ["подогрев сиденья", "подогрев сидений", "обогрев сидений"],
    negative: ["двигател", "патрубок", "ленточный", "термос", "кружка"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Электрические подогревы сидений без моторных подогревателей."
  }),
  family({
    id: "comfort_accessories",
    label: "Комфортные аксессуары салона",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["подушка", "подголовник", "подголовники", "подлокотник", "массажер", "массажёр"],
    contextAny: ["шею", "сидень", "сиден", "детская", "массаж", "салон", "подголовник", "спинка"],
    strongPhrases: ["подушка под шею", "подушка на подголовник", "подлокотник", "массажер на сидение", "массажёр"],
    negative: ["двигател", "двиг.", "коробк", "шарнир", "охладител", "стабилиз"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.83,
    description: "Подушки, подголовники и подлокотники салона без агрегатных подушек."
  }),
  family({
    id: "storage_accessories",
    label: "Органайзеры и сумки",
    categorySlug: "aksessuary",
    subcategorySlug: "organayzery",
    requiredAny: ["сумка", "сумки", "карман", "органайзер", "термосумка"],
    contextAny: ["документ", "автомобилист", "телефон", "cd", "багажник", "салон", "холодильник"],
    strongPhrases: ["сумка автомобилиста", "сумка для документов", "карман под телефон", "термосумка"],
    negative: ["двигател", "коробк", "подушка"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Сумки, карманы и органайзеры салона/багажника."
  }),
  family({
    id: "auxiliary_lighting",
    label: "Дополнительное освещение",
    categorySlug: "elektrika",
    subcategorySlug: "osveshchenie",
    requiredAny: ["маяк", "такси", "подсветка", "габариты"],
    contextAny: ["12", "24", "диод", "led", "салон", "номер", "магнит", "импульс"],
    strongPhrases: ["маяк проблесковый", "маяк на магните", "такси подсветка", "подсветка номера"],
    negative: ["стекло", "часы"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Дополнительное автомобильное освещение, маяки и подсветка."
  }),
  family({
    id: "fuel_management",
    label: "Узлы топливной системы",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "toplivnaya-sistema",
    requiredAny: ["адсорбер", "экономайзер", "дроссель", "бензолюк"],
    strongPhrases: ["клапан адсорбера", "ремкомплект экономайзера", "ремкомплект дросселя", "отбойник бензолюка"],
    negative: ["фильтр"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Адсорберы, дроссельные и экономайзерные узлы топливной системы."
  }),
  family({
    id: "air_intake_engine_parts",
    label: "Воздухоочистители и впуск",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["воздухоочиститель", "коллектор", "влагоотделитель"],
    contextAny: ["впуск", "двигател", "карбюратор", "инжектор"],
    strongPhrases: ["коллектор впускной", "воздухоочиститель", "отвод воздухоочистителя"],
    negative: ["выпуск", "глушител", "вакуумный усилитель"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Впускные коллекторы, воздухоочистители и связанные детали двигателя."
  }),
  family({
    id: "engine_rotating_parts",
    label: "Маховики, рокеры и малые детали двигателя",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["маховик", "рокер", "рокера", "роккера", "сухарик", "сухарики", "коромысло"],
    contextAny: ["двигател", "клапан", "вала", "москвич", "нива", "ваз"],
    strongPhrases: ["венец маховика", "сухарик клапанов", "рокера", "вал коромысла"],
    negative: ["инструмент"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Узкие моторные детали с подтверждаемым двигательным контекстом."
  }),
  family({
    id: "engine_piston_rings_generic",
    label: "Поршневые кольца",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["кольца", "кольцо"],
    contextAny: ["кострома", "стк", "mahle", "приора", "ваз", "двигател", "поршн"],
    strongPhrases: ["кольца кострома", "кольца стк", "кольца mahle", "кольца ваз", "кольца поршневые"],
    negative: ["динамик", "приемной", "глушител", "топлив", "форсун"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.84,
    description: "Кольца с моторными брендами/моделями идут группой в детали двигателя, без автопубликации."
  }),
  family({
    id: "distributor_drive_parts",
    label: "Привод трамблера",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["привод"],
    contextAny: ["трамблер", "трамблёр"],
    strongPhrases: ["привод трамблера", "привод трамблёра"],
    negative: ["скоба", "уголек", "уголёк", "подшипник"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.84,
    description: "Привод трамблера имеет однородные активные аналоги в деталях двигателя, но подтверждается группой."
  }),
  family({
    id: "wiper",
    label: "Стеклоочистители",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["дворник", "дворники", "стеклоочиститель", "стеклооч", "щетка", "щетки", "щётка", "щётки", "поводок"],
    contextAny: ["стеклоочист", "очистител", "с/очист", "дворник", "каркасн", "бескаркасн", "гибридн", "задний"],
    strongPhrases: ["щетка стеклоочистителя", "щетки стеклоочистителя", "поводок стеклоочистителя", "поводок"],
    negative: ["генератор", "стартера", "электродвигателя", "снега", "мытья", "телескопическая"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.9,
    description: "Щетки и элементы стеклоочистителя."
  }),
  family({
    id: "wheel_accessories",
    label: "Шины и диски",
    categorySlug: "aksessuary",
    subcategorySlug: "shiny-i-diski",
    requiredAny: ["колпак", "колпаки", "грибок"],
    contextAny: ["колес", "колесн", "диск", "шин", "ремонт"],
    strongPhrases: ["колпаки колес", "гайка колес", "грибок для ремонта шин", "жгут для ремонта шин"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.85,
    description: "Колёсные аксессуары и принадлежности ремонта шин."
  }),
  family({
    id: "washer_reservoir",
    label: "Бачки омывателя",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["бачок"],
    contextAny: ["омывател"],
    strongPhrases: ["бачок омывателя"],
    negative: ["расширител", "топлив", "тормоз"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Бачки омывателя выделяются по устойчивой фразе и не смешиваются с расширительными или топливными бачками."
  }),
  family({
    id: "oil_pan_plugs",
    label: "Пробки поддона",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["пробка"],
    contextAny: ["поддон"],
    strongPhrases: ["пробка поддона", "пробка сливная поддона"],
    negative: ["кпп", "коробк", "радиатор", "бачок"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Сливные пробки поддона двигателя с явным контекстом поддона."
  }),
  family({
    id: "timing_chain_parts",
    label: "Натяжители и элементы цепи",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["натяжитель", "башмак", "успокоитель"],
    contextAny: ["цепь", "цепи"],
    strongPhrases: ["натяжитель цепи", "башмак цепи", "успокоитель цепи"],
    negative: ["ремень"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.87,
    description: "Элементы цепного привода двигателя."
  }),
  family({
    id: "transmission_crosses",
    label: "Крестовины трансмиссии",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-transmissii",
    requiredAny: ["крестовина"],
    contextAny: ["кардан", "кард", "вала", "шрус"],
    strongPhrases: ["крестовина кардана", "крестовина кард.вала", "крестовина кард вала"],
    negative: ["рулев"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Крестовины с карданным или приводным контекстом."
  }),
  family({
    id: "universal_joint_crosses",
    label: "Крестовины",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-transmissii",
    requiredAny: ["крестовина"],
    strongPhrases: ["крестовина"],
    negative: ["руля", "рулев", "крестовина руля"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.84,
    description: "Крестовины без рулевого контекста требуют группового подтверждения."
  }),
  family({
    id: "suspension_bump_stops",
    label: "Буферы хода сжатия",
    categorySlug: "podveska",
    subcategorySlug: "prochaya-podveska",
    requiredAny: ["буфер", "отбойник"],
    contextAny: ["хода", "сжатия", "стойк", "амортизатор"],
    strongPhrases: ["буфер хода сжатия", "отбойник амортизатора", "отбойник стойки"],
    negative: ["капот", "двер", "багажник"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.84,
    description: "Буферы/отбойники подвески остаются в подтверждаемой группе из-за слабых активных аналогов."
  }),
  family({
    id: "accessory_electronics",
    label: "Автоэлектроника и устройства",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["автомагнитола", "видеорегистратор", "навигатор", "парктроник", "радар"],
    strongPhrases: ["автомагнитола", "видеорегистратор", "парктроник"],
    negative: ["провод", "карта памяти", "флеш"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.85,
    description: "Однородные группы автомобильной электроники в существующей подкатегории прочих аксессуаров."
  }),
  family({
    id: "reflectors",
    label: "Катафоты и отражатели",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "fonari",
    requiredAny: ["катафот", "отражатель"],
    negative: ["светоотражающая лента"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.86,
    description: "Катафоты и отражатели относятся к световым элементам без привязки к крепежу."
  }),
  family({
    id: "stop_lights",
    label: "Стоп-сигналы",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "fonari",
    requiredAny: ["стоп"],
    contextAny: ["сигнал", "фонар"],
    strongPhrases: ["стоп-сигнал", "стоп сигнал", "фонарь стоп-сигнала"],
    negative: ["датчик", "рамка", "номер", "спойлер", "стопор"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Световые стоп-сигналы без датчиков, рамок номера и стопоров."
  }),
  family({
    id: "automotive_horns",
    label: "Звуковые сигналы",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["сигнал", "сигналы", "ревун", "сирена"],
    contextAny: ["воздуш", "рожк", "грузов", "труба", "сирена", "ревун"],
    strongPhrases: ["сигнал воздушный", "сигналы воздушные", "сигналы 3 рожка", "сигналы 2 рожка"],
    negative: ["стоп", "датчик", "поворот", "лампа"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Звуковые автомобильные сигналы с контекстом рожков, сирены или воздушного сигнала."
  }),
  family({
    id: "hood_cables",
    label: "Тросы капота",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["трос"],
    contextAny: ["капот"],
    strongPhrases: ["трос капота"],
    negative: ["тормоз", "ручник", "газ", "сцеплен", "спидометр", "кпп"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Тросы капота в существующем кузовном target."
  }),
  family({
    id: "speedometer_cables",
    label: "Тросы спидометра",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["трос"],
    contextAny: ["спидометр"],
    strongPhrases: ["трос спидометра"],
    negative: ["газ", "тормоз", "сцеплен", "капот", "кпп"],
    autoReadyMinEvidence: 4,
    baseConfidence: 0.83,
    description: "Тросы спидометра группируются по активному legacy target и требуют подтверждения."
  }),
  family({
    id: "body_air_intakes",
    label: "Кузовные воздухозаборники",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["воздухозаборник", "воздухозаборники"],
    strongPhrases: ["воздухозаборник", "воздухозаборники хром"],
    negative: ["патрубок", "фильтр", "вакуум", "турбин", "турбокомпрессор"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Кузовные декоративные/наружные воздухозаборники без патрубков и фильтров двигателя."
  }),
  family({
    id: "sound_insulation",
    label: "Шумоизоляция",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["шумоизоляция", "виброшумоизоляция"],
    strongPhrases: ["шумоизоляция", "виброшумоизоляция"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.84,
    description: "Шумоизоляционные материалы группируются по существующему кузовному target."
  }),
  family({
    id: "wheel_fasteners",
    label: "Колёсные болты, гайки и шпильки",
    categorySlug: "aksessuary",
    subcategorySlug: "shiny-i-diski",
    requiredAny: ["болт", "гайка", "шпилька", "шайба"],
    contextAny: ["колес", "колесн", "диск"],
    strongPhrases: ["болт колеса", "болт колес", "гайка колеса", "гайка колес", "шпилька колеса"],
    negative: ["гбц", "двигател", "кпп", "кардан", "рессор", "суппорт", "генератор", "глушител"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Колёсный метиз распознаётся только при явном контексте колеса или диска."
  }),
  family({
    id: "hub_hardware",
    label: "Ступичные метизы и элементы",
    categorySlug: "podveska",
    subcategorySlug: "stupicy",
    requiredAny: ["болт", "гайка", "шпилька", "шайба", "втулка", "кольцо"],
    contextAny: ["ступиц", "ступичн", "кулак", "цапф"],
    strongPhrases: ["гайка ступицы", "болт ступицы", "шпилька ступицы", "кольцо ступицы"],
    negative: ["колес", "кпп", "кардан", "гбц", "сцеплен", "суппорт"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.84,
    description: "Ступичные крепёжные и малые элементы без смешения с колёсными аксессуарами."
  }),
  family({
    id: "engine_fasteners",
    label: "Метизы и малые детали двигателя",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["болт", "гайка", "шпилька", "шайба", "втулка", "кольцо", "заглушка"],
    contextAny: ["гбц", "голов", "блок", "двигател", "коленвал", "распредвал", "клапан", "поршн", "маховик", "шкив"],
    strongPhrases: [
      "болт гбц",
      "болт головки",
      "шпилька гбц",
      "кольцо поршневое",
      "заглушка блока",
      "втулка распредвала"
    ],
    negative: [
      "кардан",
      "кпп",
      "сцеплен",
      "рессор",
      "колес",
      "суппорт",
      "глушител",
      "радиатор",
      "генератор",
      "блок-фар",
      "блок фар",
      "фара",
      "фары",
      "фонар"
    ],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Широкие слова вроде болт, шайба и кольцо принимаются только с моторным контекстом."
  }),
  family({
    id: "engine_mount_hardware",
    label: "Опоры и кронштейны двигателя",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["кронштейн", "опора", "подушка", "ремкомплект"],
    contextAny: ["двигател", "двс", "силов"],
    strongPhrases: ["кронштейн опоры двигателя", "задней опоры двигателя", "правой опоры двигателя", "опора двигателя"],
    negative: ["амортизатор", "стойк", "салон", "сидень"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.84,
    description: "Опоры и кронштейны двигателя группируются в детали двигателя только при явном двигательном контексте."
  }),
  family({
    id: "kpp_hardware",
    label: "Метизы и малые детали КПП",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "kpp",
    requiredAny: ["болт", "гайка", "шпилька", "шайба", "втулка", "кольцо", "вилка", "шток"],
    contextAny: ["кпп", "коробк", "передач", "первичн", "вторичн", "синхронизатор"],
    strongPhrases: ["болт кпп", "гайка кпп", "втулка кпп", "кольцо синхронизатора", "шток выбора передач"],
    negative: ["сцеплен", "кардан", "колес", "рессор", "радиатор"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.84,
    description: "КПП-контекст отделяет малые детали коробки от сцепления и общей трансмиссии."
  }),
  family({
    id: "transmission_hardware",
    label: "Метизы и малые детали трансмиссии",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-transmissii",
    requiredAny: ["болт", "гайка", "шпилька", "шайба", "втулка", "кольцо", "сальник", "фланец"],
    contextAny: ["кардан", "шрус", "полуос", "редуктор", "раздат", "мост", "дифференциал", "привод"],
    strongPhrases: ["болт кардана", "сальник полуоси", "фланец редуктора", "кольцо шруса", "гайка хвостовика"],
    negative: ["кпп", "сцеплен", "колес", "рессор", "суппорт", "двигател", "диод", "термостат", "термостой"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Малые элементы трансмиссии группируются только при явном узловом контексте."
  }),
  family({
    id: "axle_bridge_parts",
    label: "Детали мостов",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-transmissii",
    requiredAny: ["мост", "моста", "чулок", "редуктор"],
    contextAny: ["зад", "перед", "ведущ", "главн", "передач"],
    strongPhrases: ["заднего моста", "переднего моста", "чулок моста", "главная передача"],
    negative: ["диод", "термостат", "термостой", "подогрев", "салон"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Детали переднего/заднего моста без диодных мостов и термо-слов."
  }),
  family({
    id: "spring_hardware",
    label: "Метизы и втулки рессор",
    categorySlug: "podveska",
    subcategorySlug: "ressory",
    requiredAny: ["болт", "гайка", "шпилька", "шайба", "втулка", "стремянка", "серьга"],
    contextAny: ["рессор", "лист", "стремян", "серьг"],
    strongPhrases: ["болт рессоры", "втулка рессоры", "гайка стремянки", "стремянка рессоры", "серьга рессоры"],
    negative: ["кпп", "двигател", "генератор", "суппорт", "глушител"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Рессорные крепёжные элементы и втулки отделяются от универсального крепежа."
  }),
  family({
    id: "generator_hardware",
    label: "Метизы генератора",
    categorySlug: "elektrika",
    subcategorySlug: "generatory",
    requiredAny: ["болт", "гайка", "шпилька", "шайба", "втулка", "крышка"],
    contextAny: ["генератор", "генер"],
    strongPhrases: ["болт генератора", "крышка генератора", "втулка генератора", "шайба генератора"],
    negative: ["ремень", "стартер", "кпп", "двигател", "рессор"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.84,
    description: "Малые элементы генератора получают цель только при явном генераторном контексте."
  }),
  family({
    id: "alternator_diode_bridge_hardware",
    label: "Диодные мосты генератора",
    categorySlug: "elektrika",
    subcategorySlug: "generatory",
    requiredAny: ["мост", "болт"],
    contextAny: ["диод"],
    strongPhrases: ["диодный мост", "диодного моста", "болт диодного моста"],
    negative: ["задний мост", "передний мост", "мост кардан"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.85,
    description: "Диодный мост относится к генератору; похожие мосты трансмиссии исключаются отрицательными признаками."
  }),
  family({
    id: "clutch_parts",
    label: "Детали сцепления",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "sceplenie",
    requiredAny: ["диск", "болт", "гайка", "шпилька", "шайба", "муфта", "вилка", "подшипник"],
    contextAny: ["сцеплен", "выжимн", "пгу"],
    strongPhrases: ["диск сцепления", "болт сцепления", "муфта выжимная", "вилка сцепления", "подшипник выжимной"],
    negative: ["тормоз", "кпп", "кардан", "колес"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Сцепление требует предметного контекста, чтобы не спутать диск или подшипник с другими разделами."
  }),
  family({
    id: "clutch_cables",
    label: "Тросы сцепления",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "sceplenie",
    requiredAny: ["трос"],
    contextAny: ["сцеплен"],
    strongPhrases: ["трос сцепления"],
    negative: ["тормоз", "газ", "спидометр", "капот", "кпп"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.87,
    description: "Тросы сцепления с явным контекстом сцепления."
  }),
  family({
    id: "parking_brake_cables",
    label: "Тросы ручного тормоза",
    categorySlug: "tormoznaya-sistema",
    subcategorySlug: "ruchnoy-tormoz",
    requiredAny: ["трос", "ремкомплект"],
    contextAny: ["ручник", "стояноч", "тормоз"],
    strongPhrases: ["трос ручника", "трос ручного тормоза", "трос стояночного тормоза", "ремкомплект стояночного тормоза"],
    negative: ["газ", "сцеплен", "спидометр", "капот"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.87,
    description: "Тросы и ремкомплекты стояночного тормоза."
  }),
  family({
    id: "brake_fittings",
    label: "Тормозные штуцеры и трубки",
    categorySlug: "tormoznaya-sistema",
    subcategorySlug: "tormoznye-shtucery",
    requiredAny: ["штуцер", "фитинг", "тройник", "трубка", "шланг"],
    contextAny: ["тормоз", "суппорт", "цилиндр"],
    strongPhrases: ["штуцер тормозной", "трубка тормозная", "тройник тормозной", "шланг тормозной"],
    negative: ["топлив", "радиатор", "охлажд", "гур"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Тормозные штуцеры, тройники и трубки с обязательным тормозным контекстом."
  }),
  family({
    id: "copper_brake_tubes",
    label: "Медные тормозные трубки",
    categorySlug: "tormoznaya-sistema",
    subcategorySlug: "tormoznye-trubki",
    requiredAny: ["трубка", "трубки"],
    contextAny: ["медн", "иномарок", "д.5"],
    strongPhrases: ["трубки медные", "трубка медная", "медные трубки"],
    negative: ["топлив", "кондиционер", "охлажд"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.85,
    description: "Медные трубки d5 для иномарок выделяются в тормозные трубки только как группа подтверждения."
  }),
  family({
    id: "brake_bleeders",
    label: "Штуцеры и болты прокачки",
    categorySlug: "tormoznaya-sistema",
    subcategorySlug: "tormoznye-shtucery",
    requiredAny: ["штуцер", "болт"],
    contextAny: ["прокач"],
    strongPhrases: ["штуцер прокачки", "болт прокачки"],
    negative: ["масло", "поддон", "кпп"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Тормозные штуцеры/болты прокачки как узкая группа тормозной системы."
  }),
  family({
    id: "pneumatic_line_fittings",
    label: "Пневмофитинги и соединители шлангов",
    categorySlug: "tormoznaya-sistema",
    subcategorySlug: "prochaya-tormoznaya-sistema",
    requiredAny: [
      "соединитель",
      "штуцер-соединитель",
      "фитинг-соединитель",
      "быстросъемное",
      "быстросъем",
      "быстросъём",
      "фурнитура"
    ],
    contextAny: ["шланг", "шлангов", "труб", "резьба", "резьбой", "метал", "латун", "свд", "вал"],
    strongPhrases: [
      "соединитель шлангов",
      "соединитель труб",
      "наружная резьба",
      "внутренняя резьба",
      "фитинг-соединитель"
    ],
    negative: ["usb", "220v", "прикурив", "телефон", "samsung", "iphone"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.85,
    description: "Шланговые соединители и фурнитура с резьбой формируют узкие пневмо-группы без автопубликации."
  }),
  family({
    id: "brake_caliper_hardware",
    label: "Метизы и ремкомплекты суппортов",
    categorySlug: "tormoznaya-sistema",
    subcategorySlug: "supporty",
    requiredAny: ["болт", "гайка", "шпилька", "шайба", "скоба", "ремкомплект"],
    contextAny: ["суппорт"],
    strongPhrases: ["болт суппорта", "скоба суппорта", "ремкомплект суппорта"],
    negative: ["кпп", "кардан", "рессор", "генератор", "колес"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Суппортный контекст отделяет тормозные метизы от общих метизов."
  }),
  family({
    id: "cooling_fittings",
    label: "Патрубки, шланги и штуцеры охлаждения",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "patrubki-i-shlangi-ohlazhdeniya",
    requiredAny: ["патрубок", "шланг", "тройник", "соединитель", "штуцер", "фитинг"],
    contextAny: ["радиатор", "охлажд", "печк", "отопител"],
    strongPhrases: ["патрубок радиатора", "шланг радиатора", "тройник радиатора", "штуцер радиатора", "патрубок печки"],
    negative: ["тормоз", "топлив", "гур", "выхлоп"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Соединители охлаждения требуют контекст радиатора, печки или охлаждения."
  }),
  family({
    id: "cooling_clamps",
    label: "Хомуты охлаждения",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "homuty-ohlazhdeniya",
    requiredAny: ["хомут"],
    contextAny: ["радиатор", "патруб", "охлажд", "шланг"],
    strongPhrases: ["хомут радиатора", "хомут патрубка", "хомут охлаждения"],
    negative: ["глушител", "выхлоп", "тормоз"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Хомуты попадают в охлаждение только при явном контексте охлаждения."
  }),
  family({
    id: "cooling_caps",
    label: "Крышки и пробки охлаждения",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "kryshki-i-probki-ohlazhdeniya",
    requiredAny: ["крышка", "пробка"],
    contextAny: ["радиатор", "расширител", "бачок", "охлажд"],
    strongPhrases: ["крышка радиатора", "пробка радиатора", "крышка расширительного бачка", "пробка бачка охлаждения"],
    negative: ["бардач", "трамблер", "фара", "фонар", "гбц"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Крышки и пробки охлаждения отделяются от салонных, моторных и оптических крышек."
  }),
  family({
    id: "exhaust_hardware",
    label: "Метизы и хомуты выхлопной системы",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "vyhlopnaya-sistema",
    requiredAny: ["хомут", "прокладка", "кольцо", "гайка", "болт", "шпилька", "труба", "патрубок", "кронштейн", "ремкомплект"],
    contextAny: ["глушител", "резонатор", "выхлоп", "выпуск", "выпускной", "приемн", "катализатор", "коллектор", "гофра"],
    strongPhrases: [
      "хомут глушителя",
      "прокладка глушителя",
      "кольцо глушителя",
      "труба приемная",
      "приемной трубы",
      "патрубок выпускной",
      "труба выхлопная"
    ],
    negative: ["радиатор", "охлажд", "тормоз", "суппорт", "колес"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Выхлопные метизы и хомуты требуют контекста выпуска или глушителя."
  }),
  family({
    id: "other_products_fasteners",
    label: "Прочие товары: универсальные метизы",
    categorySlug: "ves-assortiment",
    subcategorySlug: "other-products",
    requiredAny: [
      "болт",
      "болты",
      "гайка",
      "гайки",
      "шайба",
      "шайбы",
      "винт",
      "винты",
      "шпилька",
      "шпильки",
      "штифт",
      "штифты",
      "заклепка",
      "заклепки",
      "заклеп"
    ],
    strongPhrases: [
      "болт",
      "гайка",
      "шайба",
      "винт",
      "шпилька",
      "штифт",
      "заклепка",
      "болт din",
      "винт din"
    ],
    optional: ["din", "оцинк", "нержав", "мебельн", "метрическ", "шестигран"],
    negative: otherProductsNegativeContext,
    groupable: true,
    autoReadyMinEvidence: 2,
    baseConfidence: 0.92,
    description: "Универсальные метизы без автомобильного узлового контекста отправляются в скрытую подкатегорию Прочие товары."
  }),
  family({
    id: "other_products_fittings",
    label: "Прочие товары: универсальные фитинги и соединители",
    categorySlug: "ves-assortiment",
    subcategorySlug: "other-products",
    requiredAny: [
      "фитинг",
      "фитинги",
      "штуцер",
      "штуцеры",
      "переходник",
      "переходники",
      "соединитель",
      "соединители",
      "адаптер",
      "адаптеры",
      "муфта",
      "муфты",
      "тройник",
      "тройники",
      "ниппель",
      "ниппели",
      "кольцо",
      "кольца"
    ],
    strongPhrases: [
      "фитинг",
      "штуцер",
      "переходник",
      "соединитель",
      "адаптер",
      "муфта",
      "тройник",
      "ниппель",
      "уплотнительное кольцо"
    ],
    optional: ["прямой", "угловой", "латун", "резьба", "наружная", "внутренняя", "уплотн"],
    negative: otherProductsNegativeContext,
    groupable: true,
    autoReadyMinEvidence: 2,
    baseConfidence: 0.91,
    description: "Универсальные фитинги, переходники и соединители без назначения к системе относятся к Прочим товарам."
  }),
  family({
    id: "other_products_clamps_brackets",
    label: "Прочие товары: универсальные хомуты и держатели",
    categorySlug: "ves-assortiment",
    subcategorySlug: "other-products",
    requiredAny: [
      "хомут",
      "хомуты",
      "зажим",
      "зажимы",
      "скоба",
      "скобы",
      "клипса",
      "клипсы",
      "фиксатор",
      "фиксаторы",
      "кронштейн",
      "кронштейны",
      "крепление",
      "крепления"
    ],
    strongPhrases: [
      "хомут",
      "зажим",
      "скоба",
      "клипса",
      "фиксатор",
      "кронштейн",
      "крепление"
    ],
    optional: ["универсальный", "металлический", "пластиковый", "червячный", "пружинный"],
    negative: otherProductsNegativeContext,
    groupable: true,
    autoReadyMinEvidence: 2,
    baseConfidence: 0.9,
    description: "Универсальные хомуты, зажимы и держатели без системного контекста относятся к Прочим товарам."
  }),
  family({
    id: "engine_caps",
    label: "Крышки и заглушки двигателя",
    categorySlug: "dvigatel-i-transmissiya",
    subcategorySlug: "detali-dvigatelya",
    requiredAny: ["крышка", "пробка", "заглушка"],
    contextAny: ["масляный", "горловин", "сапун", "тнвд", "воздухоочистител"],
    strongPhrases: ["крышка масляной горловины", "крышка сапуна", "заглушка тнвд", "крышка воздухоочистителя"],
    negative: ["радиатор", "бачок", "фара", "фонар", "бардач"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.84,
    description: "Крышки и заглушки двигателя группируются только по моторному контексту горловины, сапуна, ТНВД или воздухоочистителя."
  }),
  family({
    id: "optics_caps",
    label: "Крышки и заглушки оптики",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kryshki-i-korpusa-optiki",
    requiredAny: ["крышка", "заглушка", "кожух"],
    contextAny: ["фар", "фары", "фонар", "противотуман", "блок-фар", "блокфар"],
    strongPhrases: ["заглушка блок-фар", "крышка фары", "крышка фонаря", "заглушка противотуманок"],
    negative: ["лампа", "болт", "крепление"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.84,
    description: "Крышки и заглушки фар/фонарей отделены от моторных и охлаждающих крышек."
  }),
  family({
    id: "tools",
    label: "Инструменты",
    categorySlug: "aksessuary",
    subcategorySlug: "instrumenty",
    requiredAny: ["ключ", "головка", "съемник", "щуп", "домкрат", "трещотка", "полировочная", "наждачный", "паста"],
    strongPhrases: ["ключ свечной", "головка торцевая", "съемник подшипника", "полировочная машина", "наждачный круг", "паста притирочная"],
    negative: ["ключ зажигания"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.88,
    description: "Инструменты и принадлежности для обслуживания."
  }),
  family({
    id: "interior",
    label: "Элементы салона",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "elementy-salona",
    requiredAny: ["консоль", "полка", "обшивка", "накладка", "пепельница", "бардачок", "сиденье", "козырек", "козырьки", "сопло", "обдув"],
    strongPhrases: ["полка задняя", "обшивка двери", "накладка салона", "крышка бардачка", "козырьки солнцезащитные", "сопло обдува"],
    negative: ["фары", "фонаря", "бампера", "крыла"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.85,
    description: "Салонные полки, консоли, обшивки и накладки."
  }),
  family({
    id: "body_locks_handles",
    label: "Замки и ручки",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "zamki-i-ruchki",
    requiredAny: ["ручка", "замок", "личинка", "привод"],
    contextAny: ["двер", "багажник", "капот", "сидень", "бак", "стеклопод", "замка", "личинок"],
    strongPhrases: ["ручка двери", "замок двери", "привод замка", "набор личинок", "ручка стеклоподъемника"],
    negative: ["инструмент", "руль", "педал", "центральный", "сигнализация"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.86,
    description: "Дверные ручки, замки и личинки."
  }),
  family({
    id: "body_clips",
    label: "Пистоны и фиксаторы кузова",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["пистон", "пистоны", "фиксатор", "скоба"],
    contextAny: ["двер", "обшивк", "багажник", "потолок", "панел", "эмблем", "салон"],
    strongPhrases: ["пистоны дверные", "пистоны двери", "пистоны обшивки", "скоба крепления панели"],
    negative: ["тормоз", "трубок", "молдинг", "подкрыл", "бампер"],
    autoReadyMinEvidence: 99,
    baseConfidence: 0.82,
    description: "Кузовные пистоны и фиксаторы сгруппированы только при кузовном контексте."
  }),
  family({
    id: "body_glass",
    label: "Стекла",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "stekla",
    requiredAny: ["стекло", "стекла", "уплотнитель"],
    contextAny: ["лоб", "ветров", "зад", "бок", "двер", "окна", "ветр"],
    strongPhrases: ["стекло двери", "стекло заднее", "стекло лобовое", "уплотнитель стекла"],
    negative: ["фары", "фонаря", "лампа", "стеклоочист", "стеклоподъем", "стеклоподъём", "часы", "поводок"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.86,
    description: "Автомобильные стекла и уплотнители стекол без оптики."
  }),
  family({
    id: "optics_glass",
    label: "Стекла фар и фонарей",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "stekla-far-i-fonarey",
    requiredAny: ["стекло", "защита"],
    contextAny: ["фар", "фонар", "противотуман"],
    strongPhrases: ["стекло фары", "стекло фонаря", "защита фар", "защита задних фар"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.88,
    description: "Стекла и защитные элементы фар/фонарей."
  }),
  family({
    id: "body_brackets",
    label: "Кронштейны и крепления кузова",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kronshteyny-i-krepleniya",
    requiredAny: ["кронштейн", "скоба", "крепление"],
    contextAny: ["фар", "фонар", "бампер", "салон", "номер", "кузов", "двер"],
    strongPhrases: ["кронштейн фары", "кронштейн бампера", "скоба фары", "крепление бампера"],
    negative: ["двигателя", "генератора", "рессоры", "суппорта", "фаркоп"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.84,
    description: "Кузовные кронштейны и крепления с явным контекстом."
  }),
  family({
    id: "washer_jets",
    label: "Форсунки и жиклеры омывателя",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["форсунка", "жиклер", "жеклер", "распылитель", "распределитель"],
    contextAny: ["омывател"],
    strongPhrases: ["форсунка омывателя", "жиклер омывателя", "жеклер омывателя", "распылитель омывателя"],
    negative: ["топлив", "бензин", "форсунки топлив"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.86,
    description: "Мелкие элементы омывателя без смешения с топливными форсунками."
  }),
  family({
    id: "headlight_decor",
    label: "Декор и ободки фар",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "obves-i-dekor",
    requiredAny: ["реснички", "ресничка", "ободок", "накладка", "надставка"],
    contextAny: ["фар", "фары"],
    strongPhrases: ["реснички фар", "накладка фар", "ободок фар", "надставка фар"],
    negative: ["болт", "крепление", "набор крепления", "лампа"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Декоративные элементы фар без крепежных наборов и ламп."
  }),
  family({
    id: "body_small_exterior",
    label: "Малые кузовные элементы",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["жабо", "форточка", "боковина", "бархотка", "уголок"],
    contextAny: ["стекол", "стекла", "боковая", "передний", "задний", "левая", "правая", "ваз", "ока", "нива"],
    strongPhrases: ["жабо", "форточка раздвижная", "боковина левая", "бархотка стекол"],
    negative: ["латун", "резьба", "гайка", "фитинг", "штуцер", "тройник"],
    autoReadyMinEvidence: 3,
    baseConfidence: 0.85,
    description: "Малые кузовные элементы с кузовным/стекольным контекстом."
  }),
  family({
    id: "body_exterior",
    label: "Кузовные детали",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "kuzovnye-detali",
    requiredAny: ["арка", "арки", "крыло", "капот", "дверь", "панель", "порог", "водосток"],
    strongPhrases: ["арка колеса", "арки колес", "панель задняя", "крыло переднее", "порог кузова", "водосток"],
    negative: ["обшивка"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.85,
    description: "Крупные кузовные элементы."
  }),
  family({
    id: "body_decor",
    label: "Обвес и декор",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "obves-i-dekor",
    requiredAny: ["кенгурятник", "молдинг", "накладка", "спойлер", "дефлектор", "ветровик", "расширитель", "сетка", "реснички"],
    contextAny: ["арк", "бампер", "порог", "капот", "фар", "стекол", "воздухозабор", "кузов", "наруж", "алюмини", "пластиков"],
    strongPhrases: ["кенгурятник", "ветровик", "расширитель арок", "сетка алюминиевая", "сетка пластиковая", "накладка бампера", "накладка порога", "дефлектор капота"],
    negative: ["салона", "радиатор", "фильтр", "стекла", "кулисы", "сидень", "потолка", "пепельниц", "поводка"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.85,
    description: "Декоративные и защитные кузовные элементы."
  }),
  family({
    id: "auto_chemistry",
    label: "Автохимия",
    categorySlug: "aksessuary",
    subcategorySlug: "avtohimiya",
    requiredAny: ["герметик", "очиститель", "промывка", "смазка", "полироль", "краска", "эмаль", "лак", "антикор"],
    strongPhrases: ["преобразователь ржавчины", "очиститель карбюратора", "очиститель тормозов"],
    negative: ["подкраска"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.9,
    description: "Автохимия, краски, очистители и составы."
  }),
  family({
    id: "misc_accessories",
    label: "Прочие аксессуары",
    categorySlug: "aksessuary",
    subcategorySlug: "prochie-aksessuary",
    requiredAny: ["фаркоп", "прицепное", "канистра", "тонировка", "пленка", "рамка"],
    strongPhrases: ["пленка тонировочная", "рамка номера", "прицепное устройство"],
    negative: ["ремкомплект", "двигателя"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.85,
    description: "Аксессуары с явными предметными словами."
  }),
  family({
    id: "tire",
    label: "Шины",
    categorySlug: "aksessuary",
    subcategorySlug: "shiny-i-diski",
    requiredAny: ["шина", "шины", "а/шина", "резина"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.93,
    description: "Автошины."
  }),
  family({
    id: "wheel_disc",
    label: "Колесные диски",
    categorySlug: "aksessuary",
    subcategorySlug: "shiny-i-diski",
    requiredAny: ["диск"],
    requiredAll: ["колесный"],
    strongPhrases: ["диск колесный", "колесный диск", "литые диски"],
    negative: ["тормозной", "сцепления"],
    autoReadyMinEvidence: 2,
    baseConfidence: 0.92,
    description: "Колесные диски; тормозные диски исключаются."
  }),
  family({
    id: "headlight",
    label: "Фары",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "fary",
    requiredAny: ["фара", "фары", "блок-фара", "блокфара"],
    strongPhrases: ["блок фара", "блок-фара"],
    negative: ["стекло", "кронштейн", "лампа"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.9,
    description: "Фары без контекста стекла или крепления."
  }),
  family({
    id: "mirror",
    label: "Зеркала",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "zerkala",
    requiredAny: ["зеркало", "зеркал"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.91,
    description: "Автомобильные зеркала."
  }),
  family({
    id: "bumper",
    label: "Бамперы",
    categorySlug: "kuzov-i-optika",
    subcategorySlug: "bampery",
    requiredAny: ["бампер"],
    negative: ["кронштейн"],
    autoReadyMinEvidence: 1,
    baseConfidence: 0.9,
    description: "Бамперы без крепежного контекста."
  })
];

function family(input: Omit<ProductFamilyDefinition, "groupable"> & { groupable?: boolean }) {
  return {
    groupable: true,
    ...input
  };
}
