WITH synonym_seed(source_term, target_terms, is_bidirectional) AS (
  VALUES
    ('акб', ARRAY['аккумулятор', 'аккумуляторы', 'аккумуляторная батарея']::text[], true),
    ('аккум', ARRAY['аккумулятор', 'аккумуляторы', 'акб']::text[], true),
    ('akb', ARRAY['акб', 'аккумулятор', 'аккумуляторы']::text[], true),
    ('акумулятор', ARRAY['аккумулятор', 'аккумуляторы', 'акб']::text[], true),
    ('akkumulyator', ARRAY['аккумулятор', 'аккумуляторы', 'акб']::text[], true),
    ('дворники', ARRAY['дворник', 'щетка стеклоочистителя', 'щётка стеклоочистителя', 'стеклоочиститель', 'поводок стеклоочистителя']::text[], true),
    ('dvorniki', ARRAY['дворники', 'дворник', 'щетка стеклоочистителя']::text[], true),
    ('щетки', ARRAY['щетка стеклоочистителя', 'щётка стеклоочистителя', 'дворники']::text[], true),
    ('масло', ARRAY['масла', 'моторное масло', 'двигательное масло', 'автомасло']::text[], true),
    ('maslo', ARRAY['масло', 'масла', 'моторное масло']::text[], true),
    ('тормозуха', ARRAY['тормозная жидкость', 'жидкость тормозная']::text[], true),
    ('охлаждайка', ARRAY['антифриз', 'тосол', 'охлаждающая жидкость']::text[], true),
    ('гур', ARRAY['гидроусилитель', 'жидкость гур', 'шланг гур']::text[], true),
    ('птф', ARRAY['противотуманки', 'противотуманные фары']::text[], true),
    ('грм', ARRAY['ремень грм', 'комплект грм', 'ролик грм']::text[], true),
    ('шрус', ARRAY['граната', 'шарнир равных угловых скоростей']::text[], true),
    ('кпп', ARRAY['коробка передач', 'мкпп', 'трансмиссия']::text[], true),
    ('сцепа', ARRAY['сцепление', 'комплект сцепления']::text[], true),
    ('резина', ARRAY['а/шина', 'а/шины', 'шина', 'шины']::text[], false),
    ('шины', ARRAY['а/шина', 'а/шины', 'резина']::text[], true),
    ('литые диски', ARRAY['диск колесный', 'колесный диск']::text[], true),
    ('печка', ARRAY['отопитель', 'мотор печки', 'радиатор печки']::text[], true),
    ('бензобак', ARRAY['бак топливный', 'топливный бак']::text[], true),
    ('bosch', ARRAY['бош']::text[], true),
    ('mann', ARRAY['манн']::text[], true),
    ('ngk', ARRAY['нжк', 'энжикей']::text[], true),
    ('osram', ARRAY['осрам']::text[], true),
    ('sct', ARRAY['стс']::text[], true),
    ('avs', ARRAY['авс']::text[], true),
    ('lavr', ARRAY['лавр']::text[], true),
    ('motul', ARRAY['мотюль']::text[], true),
    ('mobil', ARRAY['мобил']::text[], true),
    ('zic', ARRAY['зик']::text[], true),
    ('shell', ARRAY['шелл']::text[], true),
    ('castrol', ARRAY['кастрол']::text[], true),
    ('luxe', ARRAY['люкс']::text[], true),
    ('renault', ARRAY['рено']::text[], true),
    ('logan', ARRAY['логан']::text[], true),
    ('lada', ARRAY['лада', 'ваз']::text[], true),
    ('vaz', ARRAY['ваз', 'лада']::text[], true),
    ('gaz', ARRAY['газ']::text[], true),
    ('uaz', ARRAY['уаз']::text[], true),
    ('chevrolet', ARRAY['шевроле']::text[], true),
    ('daewoo', ARRAY['дэу', 'део']::text[], true),
    ('ford', ARRAY['форд']::text[], true),
    ('nissan', ARRAY['ниссан']::text[], true),
    ('toyota', ARRAY['тойота']::text[], true),
    ('hyundai', ARRAY['хендай', 'хундай']::text[], true),
    ('kia', ARRAY['киа']::text[], true),
    ('vw', ARRAY['фольксваген', 'volkswagen']::text[], true),
    ('volkswagen', ARRAY['фольксваген', 'vw']::text[], true)
)
INSERT INTO synonyms (source_term, target_terms, is_bidirectional, is_active)
SELECT source_term, target_terms, is_bidirectional, true
FROM synonym_seed
ON CONFLICT (source_term) DO UPDATE
SET
  target_terms = EXCLUDED.target_terms,
  is_bidirectional = EXCLUDED.is_bidirectional,
  is_active = true,
  updated_at = now();
